2023-09-22 11:32:16,375 - [opject.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-09-22 11:32:16,375 - [opject.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-09-22 11:32:16,375 - [opject.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-09-22 11:34:04,422 - [opject.py - 204] - ERROR:元素为//*[@class="ant-pagination-item-link"]获取该元素对象失败
2023-09-22 11:34:04,422 - [opject.py - 204] - ERROR:元素为//*[@class="ant-pagination-item-link"]获取该元素对象失败
2023-09-22 11:34:04,422 - [opject.py - 204] - ERROR:元素为//*[@class="ant-pagination-item-link"]获取该元素对象失败
2023-09-22 11:34:22,319 - [opject.py - 204] - ERROR:元素为//*[@class="ant-pagination-item-link"]获取该元素对象失败
2023-09-22 11:34:22,319 - [opject.py - 204] - ERROR:元素为//*[@class="ant-pagination-item-link"]获取该元素对象失败
2023-09-22 11:34:22,319 - [opject.py - 204] - ERROR:元素为//*[@class="ant-pagination-item-link"]获取该元素对象失败
2023-09-22 11:34:22,319 - [opject.py - 204] - ERROR:元素为//*[@class="ant-pagination-item-link"]获取该元素对象失败
2023-09-22 11:35:58,497 - [opject.py - 204] - ERROR:元素为//*[@class="ant-pagination-item-link"]获取该元素对象失败
2023-09-22 11:35:58,497 - [opject.py - 204] - ERROR:元素为//*[@class="ant-pagination-item-link"]获取该元素对象失败
2023-09-22 11:35:58,497 - [opject.py - 204] - ERROR:元素为//*[@class="ant-pagination-item-link"]获取该元素对象失败
2023-09-22 14:06:38,006 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025C9946D1F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/25e2dca68ed0ef5d61b8711497cf1034
2023-09-22 14:06:38,006 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025C9946D1F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/25e2dca68ed0ef5d61b8711497cf1034
2023-09-22 14:06:42,087 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025C9A050310>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/25e2dca68ed0ef5d61b8711497cf1034
2023-09-22 14:06:42,087 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025C9A050310>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/25e2dca68ed0ef5d61b8711497cf1034
2023-09-22 14:07:18,687 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017949E96430>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/7e25be813173c153c7114d79b22b1b8c
2023-09-22 14:07:18,687 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017949E96430>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/7e25be813173c153c7114d79b22b1b8c
2023-09-22 14:07:22,739 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001794A89C1C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/7e25be813173c153c7114d79b22b1b8c
2023-09-22 14:07:22,739 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001794A89C1C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/7e25be813173c153c7114d79b22b1b8c
2023-09-22 14:07:26,838 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001794A89C0D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/7e25be813173c153c7114d79b22b1b8c
2023-09-22 14:07:26,838 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001794A89C0D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/7e25be813173c153c7114d79b22b1b8c
2023-09-22 14:43:08,288 - [test_contract_aptos.py - 103] - INFO:测试编号:1,测试标题:['创建项目aptos_staking', '检查项目aptos_staking', '构建项目aptos_staking', '部署项目aptos_staking', '删除项目aptos_staking'],执行成功！
2023-09-22 14:43:08,288 - [test_contract_aptos.py - 103] - INFO:测试编号:1,测试标题:['创建项目aptos_staking', '检查项目aptos_staking', '构建项目aptos_staking', '部署项目aptos_staking', '删除项目aptos_staking'],执行成功！
2023-09-22 14:43:53,580 - [test_contract_aptos.py - 103] - INFO:测试编号:2,测试标题:['创建项目aptos_vesting', '检查项目aptos_westing', '构建项目aptos_westing', '部署项目aptos_westing', '删除项目aptos_westing'],执行成功！
2023-09-22 14:43:53,580 - [test_contract_aptos.py - 103] - INFO:测试编号:2,测试标题:['创建项目aptos_vesting', '检查项目aptos_westing', '构建项目aptos_westing', '部署项目aptos_westing', '删除项目aptos_westing'],执行成功！
2023-09-22 14:46:34,224 - [test_contract_aptos.py - 103] - INFO:测试编号:1,测试标题:['创建项目aptos_staking', '检查项目aptos_staking', '构建项目aptos_staking', '部署项目aptos_staking', '删除项目aptos_staking'],执行成功！
2023-09-22 14:46:34,224 - [test_contract_aptos.py - 103] - INFO:测试编号:1,测试标题:['创建项目aptos_staking', '检查项目aptos_staking', '构建项目aptos_staking', '部署项目aptos_staking', '删除项目aptos_staking'],执行成功！
2023-09-22 14:47:04,768 - [test_contract_aptos.py - 103] - INFO:测试编号:2,测试标题:['创建项目aptos_vesting', '检查项目aptos_westing', '构建项目aptos_westing', '部署项目aptos_westing', '删除项目aptos_westing'],执行成功！
2023-09-22 14:47:04,768 - [test_contract_aptos.py - 103] - INFO:测试编号:2,测试标题:['创建项目aptos_vesting', '检查项目aptos_westing', '构建项目aptos_westing', '部署项目aptos_westing', '删除项目aptos_westing'],执行成功！
2023-09-22 14:48:18,505 - [test_contract_aptos.py - 103] - INFO:测试编号:1,测试标题:['创建项目aptos_staking', '检查项目aptos_staking', '构建项目aptos_staking', '部署项目aptos_staking', '删除项目aptos_staking'],执行成功！
2023-09-22 14:48:18,505 - [test_contract_aptos.py - 103] - INFO:测试编号:1,测试标题:['创建项目aptos_staking', '检查项目aptos_staking', '构建项目aptos_staking', '部署项目aptos_staking', '删除项目aptos_staking'],执行成功！
2023-09-22 14:48:50,252 - [test_contract_aptos.py - 103] - INFO:测试编号:2,测试标题:['创建项目aptos_vesting', '检查项目aptos_westing', '构建项目aptos_westing', '部署项目aptos_westing', '删除项目aptos_westing'],执行成功！
2023-09-22 14:48:50,252 - [test_contract_aptos.py - 103] - INFO:测试编号:2,测试标题:['创建项目aptos_vesting', '检查项目aptos_westing', '构建项目aptos_westing', '部署项目aptos_westing', '删除项目aptos_westing'],执行成功！
2023-09-22 14:49:28,505 - [test_contract_aptos.py - 103] - INFO:测试编号:3,测试标题:['创建项目aptos_lending', '检查项目aptos_lending', '构建项目aptos_lending', '部署项目aptos_lending', '删除项目aptos_lending'],执行成功！
2023-09-22 14:49:28,505 - [test_contract_aptos.py - 103] - INFO:测试编号:3,测试标题:['创建项目aptos_lending', '检查项目aptos_lending', '构建项目aptos_lending', '部署项目aptos_lending', '删除项目aptos_lending'],执行成功！
2023-09-22 14:50:06,276 - [test_contract_aptos.py - 103] - INFO:测试编号:4,测试标题:['创建项目aptos_ToDoList', '检查项目aptos_ToDoList', '构建项目aptos_ToDoList', '部署项目aptos_ToDoList', '删除项目aptos_ToDoList'],执行成功！
2023-09-22 14:50:06,276 - [test_contract_aptos.py - 103] - INFO:测试编号:4,测试标题:['创建项目aptos_ToDoList', '检查项目aptos_ToDoList', '构建项目aptos_ToDoList', '部署项目aptos_ToDoList', '删除项目aptos_ToDoList'],执行成功！
2023-09-22 14:50:35,313 - [test_contract_aptos.py - 103] - INFO:测试编号:5,测试标题:['创建项目aptos_marketplace_contract', '检查项目aptos_marketplace_contract', '构建项目aptos_marketplace_contract', '部署项目aptos_marketplace_contract', '删除项目aptos_marketplace_contract'],执行成功！
2023-09-22 14:50:35,313 - [test_contract_aptos.py - 103] - INFO:测试编号:5,测试标题:['创建项目aptos_marketplace_contract', '检查项目aptos_marketplace_contract', '构建项目aptos_marketplace_contract', '部署项目aptos_marketplace_contract', '删除项目aptos_marketplace_contract'],执行成功！
2023-09-22 14:51:03,988 - [test_contract_aptos.py - 103] - INFO:测试编号:6,测试标题:['创建项目aptos_NFT_marketplace', '检查项目aptos_NFT_marketplace', '构建项目aptos_NFT_marketplace', '部署项目aptos_NFT_marketplace', '删除项目aptos_NFT_marketplace'],执行成功！
2023-09-22 14:51:03,988 - [test_contract_aptos.py - 103] - INFO:测试编号:6,测试标题:['创建项目aptos_NFT_marketplace', '检查项目aptos_NFT_marketplace', '构建项目aptos_NFT_marketplace', '部署项目aptos_NFT_marketplace', '删除项目aptos_NFT_marketplace'],执行成功！
2023-09-22 14:51:41,564 - [test_contract_aptos.py - 103] - INFO:测试编号:7,测试标题:['创建项目aptos_raffle', '检查项目aptos_raffle', '构建项目aptos_raffle', '部署项目aptos_raffle', '删除项目aptos_raffle'],执行成功！
2023-09-22 14:51:41,564 - [test_contract_aptos.py - 103] - INFO:测试编号:7,测试标题:['创建项目aptos_raffle', '检查项目aptos_raffle', '构建项目aptos_raffle', '部署项目aptos_raffle', '删除项目aptos_raffle'],执行成功！
2023-09-22 14:52:19,099 - [test_contract_aptos.py - 103] - INFO:测试编号:8,测试标题:['创建项目aptos_candymachine', '检查项目aptos_candymachine', '构建项目aptos_candymachine', '部署项目aptos_candymachine', '删除项目aptos_candymachine'],执行成功！
2023-09-22 14:52:19,099 - [test_contract_aptos.py - 103] - INFO:测试编号:8,测试标题:['创建项目aptos_candymachine', '检查项目aptos_candymachine', '构建项目aptos_candymachine', '部署项目aptos_candymachine', '删除项目aptos_candymachine'],执行成功！
2023-09-22 14:52:47,469 - [test_contract_aptos.py - 103] - INFO:测试编号:9,测试标题:['创建项目aptos_merkproof', '检查项目aptos_merkproof', '构建项目aptos_merkproof', '部署项目aptos_merkproof', '删除项目aptos_merkproof'],执行成功！
2023-09-22 14:52:47,469 - [test_contract_aptos.py - 103] - INFO:测试编号:9,测试标题:['创建项目aptos_merkproof', '检查项目aptos_merkproof', '构建项目aptos_merkproof', '部署项目aptos_merkproof', '删除项目aptos_merkproof'],执行成功！
2023-09-22 14:53:16,045 - [test_contract_aptos.py - 103] - INFO:测试编号:10,测试标题:['创建项目aptos_hello_blockchain', '检查项目aptos_hello_blockchain', '构建项目aptos_hello_blockchain', '部署项目aptos_hello_blockchain', '删除项目aptos_hello_blockchain'],执行成功！
2023-09-22 14:53:16,045 - [test_contract_aptos.py - 103] - INFO:测试编号:10,测试标题:['创建项目aptos_hello_blockchain', '检查项目aptos_hello_blockchain', '构建项目aptos_hello_blockchain', '部署项目aptos_hello_blockchain', '删除项目aptos_hello_blockchain'],执行成功！
2023-09-22 14:53:44,861 - [test_contract_aptos.py - 103] - INFO:测试编号:11,测试标题:['创建项目aptos_warkade', '检查项目aptos_warkade', '构建项目aptos_warkade', '部署项目aptos_warkade', '删除项目aptos_warkade'],执行成功！
2023-09-22 14:53:44,861 - [test_contract_aptos.py - 103] - INFO:测试编号:11,测试标题:['创建项目aptos_warkade', '检查项目aptos_warkade', '构建项目aptos_warkade', '部署项目aptos_warkade', '删除项目aptos_warkade'],执行成功！
2023-09-22 14:54:22,272 - [test_contract_aptos.py - 103] - INFO:测试编号:12,测试标题:['创建项目aptos_tokenv2_wrapper', '检查项目aptos_tokenv2_wrapper', '构建项目aptos_tokenv2_wrapper', '部署项目aptos_tokenv2_wrapper', '删除项目aptos_tokenv2_wrapper'],执行成功！
2023-09-22 14:54:22,272 - [test_contract_aptos.py - 103] - INFO:测试编号:12,测试标题:['创建项目aptos_tokenv2_wrapper', '检查项目aptos_tokenv2_wrapper', '构建项目aptos_tokenv2_wrapper', '部署项目aptos_tokenv2_wrapper', '删除项目aptos_tokenv2_wrapper'],执行成功！
2023-09-22 15:01:16,012 - [create_project.py - 219] - ERROR:检查或编译过长
2023-09-22 15:01:16,012 - [create_project.py - 219] - ERROR:检查或编译过长
2023-09-22 15:01:16,012 - [create_project.py - 219] - ERROR:检查或编译过长
2023-09-22 15:02:08,465 - [test_contract_aptos.py - 139] - INFO:测试编号:2,测试标题:['创建项目aptos_vesting', '检查项目aptos_westing', '构建项目aptos_westing', '部署项目aptos_westing', '删除项目aptos_westing'],执行成功！
2023-09-22 15:02:08,465 - [test_contract_aptos.py - 139] - INFO:测试编号:2,测试标题:['创建项目aptos_vesting', '检查项目aptos_westing', '构建项目aptos_westing', '部署项目aptos_westing', '删除项目aptos_westing'],执行成功！
2023-09-22 15:02:08,465 - [test_contract_aptos.py - 139] - INFO:测试编号:2,测试标题:['创建项目aptos_vesting', '检查项目aptos_westing', '构建项目aptos_westing', '部署项目aptos_westing', '删除项目aptos_westing'],执行成功！
2023-09-22 15:02:52,990 - [test_contract_aptos.py - 139] - INFO:测试编号:3,测试标题:['创建项目aptos_lending', '检查项目aptos_lending', '构建项目aptos_lending', '部署项目aptos_lending', '删除项目aptos_lending'],执行成功！
2023-09-22 15:02:52,990 - [test_contract_aptos.py - 139] - INFO:测试编号:3,测试标题:['创建项目aptos_lending', '检查项目aptos_lending', '构建项目aptos_lending', '部署项目aptos_lending', '删除项目aptos_lending'],执行成功！
2023-09-22 15:02:52,990 - [test_contract_aptos.py - 139] - INFO:测试编号:3,测试标题:['创建项目aptos_lending', '检查项目aptos_lending', '构建项目aptos_lending', '部署项目aptos_lending', '删除项目aptos_lending'],执行成功！
2023-09-22 15:03:40,361 - [test_contract_aptos.py - 139] - INFO:测试编号:4,测试标题:['创建项目aptos_ToDoList', '检查项目aptos_ToDoList', '构建项目aptos_ToDoList', '部署项目aptos_ToDoList', '删除项目aptos_ToDoList'],执行成功！
2023-09-22 15:03:40,361 - [test_contract_aptos.py - 139] - INFO:测试编号:4,测试标题:['创建项目aptos_ToDoList', '检查项目aptos_ToDoList', '构建项目aptos_ToDoList', '部署项目aptos_ToDoList', '删除项目aptos_ToDoList'],执行成功！
2023-09-22 15:03:40,361 - [test_contract_aptos.py - 139] - INFO:测试编号:4,测试标题:['创建项目aptos_ToDoList', '检查项目aptos_ToDoList', '构建项目aptos_ToDoList', '部署项目aptos_ToDoList', '删除项目aptos_ToDoList'],执行成功！
2023-09-22 15:04:25,394 - [test_contract_aptos.py - 139] - INFO:测试编号:5,测试标题:['创建项目aptos_marketplace_contract', '检查项目aptos_marketplace_contract', '构建项目aptos_marketplace_contract', '部署项目aptos_marketplace_contract', '删除项目aptos_marketplace_contract'],执行成功！
2023-09-22 15:04:25,394 - [test_contract_aptos.py - 139] - INFO:测试编号:5,测试标题:['创建项目aptos_marketplace_contract', '检查项目aptos_marketplace_contract', '构建项目aptos_marketplace_contract', '部署项目aptos_marketplace_contract', '删除项目aptos_marketplace_contract'],执行成功！
2023-09-22 15:04:25,394 - [test_contract_aptos.py - 139] - INFO:测试编号:5,测试标题:['创建项目aptos_marketplace_contract', '检查项目aptos_marketplace_contract', '构建项目aptos_marketplace_contract', '部署项目aptos_marketplace_contract', '删除项目aptos_marketplace_contract'],执行成功！
2023-09-22 15:05:09,543 - [test_contract_aptos.py - 139] - INFO:测试编号:6,测试标题:['创建项目aptos_NFT_marketplace', '检查项目aptos_NFT_marketplace', '构建项目aptos_NFT_marketplace', '部署项目aptos_NFT_marketplace', '删除项目aptos_NFT_marketplace'],执行成功！
2023-09-22 15:05:09,543 - [test_contract_aptos.py - 139] - INFO:测试编号:6,测试标题:['创建项目aptos_NFT_marketplace', '检查项目aptos_NFT_marketplace', '构建项目aptos_NFT_marketplace', '部署项目aptos_NFT_marketplace', '删除项目aptos_NFT_marketplace'],执行成功！
2023-09-22 15:05:09,543 - [test_contract_aptos.py - 139] - INFO:测试编号:6,测试标题:['创建项目aptos_NFT_marketplace', '检查项目aptos_NFT_marketplace', '构建项目aptos_NFT_marketplace', '部署项目aptos_NFT_marketplace', '删除项目aptos_NFT_marketplace'],执行成功！
2023-09-22 15:05:53,841 - [test_contract_aptos.py - 139] - INFO:测试编号:7,测试标题:['创建项目aptos_raffle', '检查项目aptos_raffle', '构建项目aptos_raffle', '部署项目aptos_raffle', '删除项目aptos_raffle'],执行成功！
2023-09-22 15:05:53,841 - [test_contract_aptos.py - 139] - INFO:测试编号:7,测试标题:['创建项目aptos_raffle', '检查项目aptos_raffle', '构建项目aptos_raffle', '部署项目aptos_raffle', '删除项目aptos_raffle'],执行成功！
2023-09-22 15:05:53,841 - [test_contract_aptos.py - 139] - INFO:测试编号:7,测试标题:['创建项目aptos_raffle', '检查项目aptos_raffle', '构建项目aptos_raffle', '部署项目aptos_raffle', '删除项目aptos_raffle'],执行成功！
2023-09-22 15:06:42,334 - [test_contract_aptos.py - 139] - INFO:测试编号:8,测试标题:['创建项目aptos_candymachine', '检查项目aptos_candymachine', '构建项目aptos_candymachine', '部署项目aptos_candymachine', '删除项目aptos_candymachine'],执行成功！
2023-09-22 15:06:42,334 - [test_contract_aptos.py - 139] - INFO:测试编号:8,测试标题:['创建项目aptos_candymachine', '检查项目aptos_candymachine', '构建项目aptos_candymachine', '部署项目aptos_candymachine', '删除项目aptos_candymachine'],执行成功！
2023-09-22 15:06:42,334 - [test_contract_aptos.py - 139] - INFO:测试编号:8,测试标题:['创建项目aptos_candymachine', '检查项目aptos_candymachine', '构建项目aptos_candymachine', '部署项目aptos_candymachine', '删除项目aptos_candymachine'],执行成功！
2023-09-22 15:07:20,744 - [test_contract_aptos.py - 139] - INFO:测试编号:9,测试标题:['创建项目aptos_merkproof', '检查项目aptos_merkproof', '构建项目aptos_merkproof', '部署项目aptos_merkproof', '删除项目aptos_merkproof'],执行成功！
2023-09-22 15:07:20,744 - [test_contract_aptos.py - 139] - INFO:测试编号:9,测试标题:['创建项目aptos_merkproof', '检查项目aptos_merkproof', '构建项目aptos_merkproof', '部署项目aptos_merkproof', '删除项目aptos_merkproof'],执行成功！
2023-09-22 15:07:20,744 - [test_contract_aptos.py - 139] - INFO:测试编号:9,测试标题:['创建项目aptos_merkproof', '检查项目aptos_merkproof', '构建项目aptos_merkproof', '部署项目aptos_merkproof', '删除项目aptos_merkproof'],执行成功！
2023-09-22 15:08:02,507 - [test_contract_aptos.py - 139] - INFO:测试编号:10,测试标题:['创建项目aptos_hello_blockchain', '检查项目aptos_hello_blockchain', '构建项目aptos_hello_blockchain', '部署项目aptos_hello_blockchain', '删除项目aptos_hello_blockchain'],执行成功！
2023-09-22 15:08:02,507 - [test_contract_aptos.py - 139] - INFO:测试编号:10,测试标题:['创建项目aptos_hello_blockchain', '检查项目aptos_hello_blockchain', '构建项目aptos_hello_blockchain', '部署项目aptos_hello_blockchain', '删除项目aptos_hello_blockchain'],执行成功！
2023-09-22 15:08:02,507 - [test_contract_aptos.py - 139] - INFO:测试编号:10,测试标题:['创建项目aptos_hello_blockchain', '检查项目aptos_hello_blockchain', '构建项目aptos_hello_blockchain', '部署项目aptos_hello_blockchain', '删除项目aptos_hello_blockchain'],执行成功！
2023-09-22 15:08:46,368 - [test_contract_aptos.py - 139] - INFO:测试编号:11,测试标题:['创建项目aptos_warkade', '检查项目aptos_warkade', '构建项目aptos_warkade', '部署项目aptos_warkade', '删除项目aptos_warkade'],执行成功！
2023-09-22 15:08:46,368 - [test_contract_aptos.py - 139] - INFO:测试编号:11,测试标题:['创建项目aptos_warkade', '检查项目aptos_warkade', '构建项目aptos_warkade', '部署项目aptos_warkade', '删除项目aptos_warkade'],执行成功！
2023-09-22 15:08:46,368 - [test_contract_aptos.py - 139] - INFO:测试编号:11,测试标题:['创建项目aptos_warkade', '检查项目aptos_warkade', '构建项目aptos_warkade', '部署项目aptos_warkade', '删除项目aptos_warkade'],执行成功！
2023-09-22 15:09:33,526 - [test_contract_aptos.py - 139] - INFO:测试编号:12,测试标题:['创建项目aptos_tokenv2_wrapper', '检查项目aptos_tokenv2_wrapper', '构建项目aptos_tokenv2_wrapper', '部署项目aptos_tokenv2_wrapper', '删除项目aptos_tokenv2_wrapper'],执行成功！
2023-09-22 15:09:33,526 - [test_contract_aptos.py - 139] - INFO:测试编号:12,测试标题:['创建项目aptos_tokenv2_wrapper', '检查项目aptos_tokenv2_wrapper', '构建项目aptos_tokenv2_wrapper', '部署项目aptos_tokenv2_wrapper', '删除项目aptos_tokenv2_wrapper'],执行成功！
2023-09-22 15:09:33,526 - [test_contract_aptos.py - 139] - INFO:测试编号:12,测试标题:['创建项目aptos_tokenv2_wrapper', '检查项目aptos_tokenv2_wrapper', '构建项目aptos_tokenv2_wrapper', '部署项目aptos_tokenv2_wrapper', '删除项目aptos_tokenv2_wrapper'],执行成功！
2023-09-22 15:10:04,850 - [opject.py - 88] - ERROR://*[@class="ant-checkbox-wrapper"]元素点击失败
2023-09-22 15:10:04,850 - [opject.py - 88] - ERROR://*[@class="ant-checkbox-wrapper"]元素点击失败
2023-09-22 15:10:04,850 - [opject.py - 88] - ERROR://*[@class="ant-checkbox-wrapper"]元素点击失败
2023-09-22 15:10:04,850 - [opject.py - 88] - ERROR://*[@class="ant-checkbox-wrapper"]元素点击失败
2023-09-22 15:10:51,844 - [test_contract_aptos.py - 186] - ERROR:测试编号:2,测试标题:['创建项目aptos_vesting', '检查项目aptos_westing', '构建项目aptos_westing', '部署项目aptos_westing', '删除项目aptos_westing'],执行失败!实际结果:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_westing_z/Dashboard\n1\nvesting\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncreate_vesting\nrelease_fund\ncreate_vesting\nparam1\nparam2\nparam3\nparam4\nparam5\nTransact\noutputs\ncopy'
2023-09-22 15:10:51,844 - [test_contract_aptos.py - 186] - ERROR:测试编号:2,测试标题:['创建项目aptos_vesting', '检查项目aptos_westing', '构建项目aptos_westing', '部署项目aptos_westing', '删除项目aptos_westing'],执行失败!实际结果:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_westing_z/Dashboard\n1\nvesting\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncreate_vesting\nrelease_fund\ncreate_vesting\nparam1\nparam2\nparam3\nparam4\nparam5\nTransact\noutputs\ncopy'
2023-09-22 15:10:51,844 - [test_contract_aptos.py - 186] - ERROR:测试编号:2,测试标题:['创建项目aptos_vesting', '检查项目aptos_westing', '构建项目aptos_westing', '部署项目aptos_westing', '删除项目aptos_westing'],执行失败!实际结果:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_westing_z/Dashboard\n1\nvesting\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncreate_vesting\nrelease_fund\ncreate_vesting\nparam1\nparam2\nparam3\nparam4\nparam5\nTransact\noutputs\ncopy'
2023-09-22 15:10:51,844 - [test_contract_aptos.py - 186] - ERROR:测试编号:2,测试标题:['创建项目aptos_vesting', '检查项目aptos_westing', '构建项目aptos_westing', '部署项目aptos_westing', '删除项目aptos_westing'],执行失败!实际结果:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_westing_z/Dashboard\n1\nvesting\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncreate_vesting\nrelease_fund\ncreate_vesting\nparam1\nparam2\nparam3\nparam4\nparam5\nTransact\noutputs\ncopy'
2023-09-22 15:10:51,846 - [test_contract_aptos.py - 187] - ERROR:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_westing_z/Dashboard\n1\nvesting\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncreate_vesting\nrelease_fund\ncreate_vesting\nparam1\nparam2\nparam3\nparam4\nparam5\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_westing_z/Dashboard\n1\nvesting\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncreate_vesting\nrelease_fund\ncreate_vesting\nparam1\nparam2\nparam3\nparam4\nparam5\nTransact\noutputs\ncopy'
2023-09-22 15:10:51,846 - [test_contract_aptos.py - 187] - ERROR:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_westing_z/Dashboard\n1\nvesting\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncreate_vesting\nrelease_fund\ncreate_vesting\nparam1\nparam2\nparam3\nparam4\nparam5\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_westing_z/Dashboard\n1\nvesting\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncreate_vesting\nrelease_fund\ncreate_vesting\nparam1\nparam2\nparam3\nparam4\nparam5\nTransact\noutputs\ncopy'
2023-09-22 15:10:51,846 - [test_contract_aptos.py - 187] - ERROR:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_westing_z/Dashboard\n1\nvesting\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncreate_vesting\nrelease_fund\ncreate_vesting\nparam1\nparam2\nparam3\nparam4\nparam5\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_westing_z/Dashboard\n1\nvesting\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncreate_vesting\nrelease_fund\ncreate_vesting\nparam1\nparam2\nparam3\nparam4\nparam5\nTransact\noutputs\ncopy'
2023-09-22 15:10:51,846 - [test_contract_aptos.py - 187] - ERROR:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_westing_z/Dashboard\n1\nvesting\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncreate_vesting\nrelease_fund\ncreate_vesting\nparam1\nparam2\nparam3\nparam4\nparam5\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_westing_z/Dashboard\n1\nvesting\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncreate_vesting\nrelease_fund\ncreate_vesting\nparam1\nparam2\nparam3\nparam4\nparam5\nTransact\noutputs\ncopy'
2023-09-22 15:11:35,185 - [test_contract_aptos.py - 186] - ERROR:测试编号:3,测试标题:['创建项目aptos_lending', '检查项目aptos_lending', '构建项目aptos_lending', '部署项目aptos_lending', '删除项目aptos_lending'],执行失败!实际结果:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_lending_z/Dashboard\n1\nborrowlend\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nborrow_select\nborrower_pay_loan\ninitiate_create_pool\nlender_claim_nft\nlender_offer\nlender_offer_cancel\nupdate_pool\nborrow_select\nparam1\nparam2\nparam3\nparam4\nTransact\noutputs\ncopy'
2023-09-22 15:11:35,185 - [test_contract_aptos.py - 186] - ERROR:测试编号:3,测试标题:['创建项目aptos_lending', '检查项目aptos_lending', '构建项目aptos_lending', '部署项目aptos_lending', '删除项目aptos_lending'],执行失败!实际结果:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_lending_z/Dashboard\n1\nborrowlend\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nborrow_select\nborrower_pay_loan\ninitiate_create_pool\nlender_claim_nft\nlender_offer\nlender_offer_cancel\nupdate_pool\nborrow_select\nparam1\nparam2\nparam3\nparam4\nTransact\noutputs\ncopy'
2023-09-22 15:11:35,185 - [test_contract_aptos.py - 186] - ERROR:测试编号:3,测试标题:['创建项目aptos_lending', '检查项目aptos_lending', '构建项目aptos_lending', '部署项目aptos_lending', '删除项目aptos_lending'],执行失败!实际结果:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_lending_z/Dashboard\n1\nborrowlend\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nborrow_select\nborrower_pay_loan\ninitiate_create_pool\nlender_claim_nft\nlender_offer\nlender_offer_cancel\nupdate_pool\nborrow_select\nparam1\nparam2\nparam3\nparam4\nTransact\noutputs\ncopy'
2023-09-22 15:11:35,185 - [test_contract_aptos.py - 186] - ERROR:测试编号:3,测试标题:['创建项目aptos_lending', '检查项目aptos_lending', '构建项目aptos_lending', '部署项目aptos_lending', '删除项目aptos_lending'],执行失败!实际结果:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_lending_z/Dashboard\n1\nborrowlend\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nborrow_select\nborrower_pay_loan\ninitiate_create_pool\nlender_claim_nft\nlender_offer\nlender_offer_cancel\nupdate_pool\nborrow_select\nparam1\nparam2\nparam3\nparam4\nTransact\noutputs\ncopy'
2023-09-22 15:11:35,188 - [test_contract_aptos.py - 187] - ERROR:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_lending_z/Dashboard\n1\nborrowlend\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nborrow_select\nborrower_pay_loan\ninitiate_create_pool\nlender_claim_nft\nlender_offer\nlender_offer_cancel\nupdate_pool\nborrow_select\nparam1\nparam2\nparam3\nparam4\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_lending_z/Dashboard\n1\nborrowlend\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nborrow_select\nborrower_pay_loan\ninitiate_create_pool\nlender_claim_nft\nlender_offer\nlender_offer_cancel\nupdate_pool\nborrow_select\nparam1\nparam2\nparam3\nparam4\nTransact\noutputs\ncopy'
2023-09-22 15:11:35,188 - [test_contract_aptos.py - 187] - ERROR:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_lending_z/Dashboard\n1\nborrowlend\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nborrow_select\nborrower_pay_loan\ninitiate_create_pool\nlender_claim_nft\nlender_offer\nlender_offer_cancel\nupdate_pool\nborrow_select\nparam1\nparam2\nparam3\nparam4\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_lending_z/Dashboard\n1\nborrowlend\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nborrow_select\nborrower_pay_loan\ninitiate_create_pool\nlender_claim_nft\nlender_offer\nlender_offer_cancel\nupdate_pool\nborrow_select\nparam1\nparam2\nparam3\nparam4\nTransact\noutputs\ncopy'
2023-09-22 15:11:35,188 - [test_contract_aptos.py - 187] - ERROR:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_lending_z/Dashboard\n1\nborrowlend\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nborrow_select\nborrower_pay_loan\ninitiate_create_pool\nlender_claim_nft\nlender_offer\nlender_offer_cancel\nupdate_pool\nborrow_select\nparam1\nparam2\nparam3\nparam4\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_lending_z/Dashboard\n1\nborrowlend\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nborrow_select\nborrower_pay_loan\ninitiate_create_pool\nlender_claim_nft\nlender_offer\nlender_offer_cancel\nupdate_pool\nborrow_select\nparam1\nparam2\nparam3\nparam4\nTransact\noutputs\ncopy'
2023-09-22 15:11:35,188 - [test_contract_aptos.py - 187] - ERROR:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_lending_z/Dashboard\n1\nborrowlend\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nborrow_select\nborrower_pay_loan\ninitiate_create_pool\nlender_claim_nft\nlender_offer\nlender_offer_cancel\nupdate_pool\nborrow_select\nparam1\nparam2\nparam3\nparam4\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_lending_z/Dashboard\n1\nborrowlend\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nborrow_select\nborrower_pay_loan\ninitiate_create_pool\nlender_claim_nft\nlender_offer\nlender_offer_cancel\nupdate_pool\nborrow_select\nparam1\nparam2\nparam3\nparam4\nTransact\noutputs\ncopy'
2023-09-22 15:12:21,975 - [test_contract_aptos.py - 186] - ERROR:测试编号:4,测试标题:['创建项目aptos_ToDoList', '检查项目aptos_ToDoList', '构建项目aptos_ToDoList', '部署项目aptos_ToDoList', '删除项目aptos_ToDoList'],执行失败!实际结果:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_ToDoList_z/Dashboard\n1\ntodolist\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncomplete_task\ncreate_list\ncreate_task\ncomplete_task\nparam1\nTransact\noutputs\ncopy'
2023-09-22 15:12:21,975 - [test_contract_aptos.py - 186] - ERROR:测试编号:4,测试标题:['创建项目aptos_ToDoList', '检查项目aptos_ToDoList', '构建项目aptos_ToDoList', '部署项目aptos_ToDoList', '删除项目aptos_ToDoList'],执行失败!实际结果:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_ToDoList_z/Dashboard\n1\ntodolist\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncomplete_task\ncreate_list\ncreate_task\ncomplete_task\nparam1\nTransact\noutputs\ncopy'
2023-09-22 15:12:21,975 - [test_contract_aptos.py - 186] - ERROR:测试编号:4,测试标题:['创建项目aptos_ToDoList', '检查项目aptos_ToDoList', '构建项目aptos_ToDoList', '部署项目aptos_ToDoList', '删除项目aptos_ToDoList'],执行失败!实际结果:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_ToDoList_z/Dashboard\n1\ntodolist\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncomplete_task\ncreate_list\ncreate_task\ncomplete_task\nparam1\nTransact\noutputs\ncopy'
2023-09-22 15:12:21,975 - [test_contract_aptos.py - 186] - ERROR:测试编号:4,测试标题:['创建项目aptos_ToDoList', '检查项目aptos_ToDoList', '构建项目aptos_ToDoList', '部署项目aptos_ToDoList', '删除项目aptos_ToDoList'],执行失败!实际结果:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_ToDoList_z/Dashboard\n1\ntodolist\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncomplete_task\ncreate_list\ncreate_task\ncomplete_task\nparam1\nTransact\noutputs\ncopy'
2023-09-22 15:12:21,978 - [test_contract_aptos.py - 187] - ERROR:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_ToDoList_z/Dashboard\n1\ntodolist\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncomplete_task\ncreate_list\ncreate_task\ncomplete_task\nparam1\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_ToDoList_z/Dashboard\n1\ntodolist\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncomplete_task\ncreate_list\ncreate_task\ncomplete_task\nparam1\nTransact\noutputs\ncopy'
2023-09-22 15:12:21,978 - [test_contract_aptos.py - 187] - ERROR:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_ToDoList_z/Dashboard\n1\ntodolist\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncomplete_task\ncreate_list\ncreate_task\ncomplete_task\nparam1\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_ToDoList_z/Dashboard\n1\ntodolist\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncomplete_task\ncreate_list\ncreate_task\ncomplete_task\nparam1\nTransact\noutputs\ncopy'
2023-09-22 15:12:21,978 - [test_contract_aptos.py - 187] - ERROR:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_ToDoList_z/Dashboard\n1\ntodolist\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncomplete_task\ncreate_list\ncreate_task\ncomplete_task\nparam1\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_ToDoList_z/Dashboard\n1\ntodolist\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncomplete_task\ncreate_list\ncreate_task\ncomplete_task\nparam1\nTransact\noutputs\ncopy'
2023-09-22 15:12:21,978 - [test_contract_aptos.py - 187] - ERROR:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_ToDoList_z/Dashboard\n1\ntodolist\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncomplete_task\ncreate_list\ncreate_task\ncomplete_task\nparam1\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_ToDoList_z/Dashboard\n1\ntodolist\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncomplete_task\ncreate_list\ncreate_task\ncomplete_task\nparam1\nTransact\noutputs\ncopy'
2023-09-22 15:13:05,008 - [test_contract_aptos.py - 186] - ERROR:测试编号:5,测试标题:['创建项目aptos_marketplace_contract', '检查项目aptos_marketplace_contract', '构建项目aptos_marketplace_contract', '部署项目aptos_marketplace_contract', '删除项目aptos_marketplace_contract'],执行失败!实际结果:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_marketplace_contract_z/Dashboard\n1\nMarketplace\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\naccept_offer_script\nbatch_buy_script\nbatch_delist_script\nbatch_list_script\nbid_script\ncancel_offer_script\nchange_token_price_script\nclaim_auction_coin_script\nclaim_auction_token_script\nclaim_offer_token_script\ninitial_auction_script\ninitial_market_script\nmake_offer_script\naccept_offer_script\nparam1\nparam2\nparam3\nparam4\nparam5\nTransact\noutputs\ncopy'
2023-09-22 15:13:05,008 - [test_contract_aptos.py - 186] - ERROR:测试编号:5,测试标题:['创建项目aptos_marketplace_contract', '检查项目aptos_marketplace_contract', '构建项目aptos_marketplace_contract', '部署项目aptos_marketplace_contract', '删除项目aptos_marketplace_contract'],执行失败!实际结果:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_marketplace_contract_z/Dashboard\n1\nMarketplace\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\naccept_offer_script\nbatch_buy_script\nbatch_delist_script\nbatch_list_script\nbid_script\ncancel_offer_script\nchange_token_price_script\nclaim_auction_coin_script\nclaim_auction_token_script\nclaim_offer_token_script\ninitial_auction_script\ninitial_market_script\nmake_offer_script\naccept_offer_script\nparam1\nparam2\nparam3\nparam4\nparam5\nTransact\noutputs\ncopy'
2023-09-22 15:13:05,008 - [test_contract_aptos.py - 186] - ERROR:测试编号:5,测试标题:['创建项目aptos_marketplace_contract', '检查项目aptos_marketplace_contract', '构建项目aptos_marketplace_contract', '部署项目aptos_marketplace_contract', '删除项目aptos_marketplace_contract'],执行失败!实际结果:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_marketplace_contract_z/Dashboard\n1\nMarketplace\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\naccept_offer_script\nbatch_buy_script\nbatch_delist_script\nbatch_list_script\nbid_script\ncancel_offer_script\nchange_token_price_script\nclaim_auction_coin_script\nclaim_auction_token_script\nclaim_offer_token_script\ninitial_auction_script\ninitial_market_script\nmake_offer_script\naccept_offer_script\nparam1\nparam2\nparam3\nparam4\nparam5\nTransact\noutputs\ncopy'
2023-09-22 15:13:05,008 - [test_contract_aptos.py - 186] - ERROR:测试编号:5,测试标题:['创建项目aptos_marketplace_contract', '检查项目aptos_marketplace_contract', '构建项目aptos_marketplace_contract', '部署项目aptos_marketplace_contract', '删除项目aptos_marketplace_contract'],执行失败!实际结果:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_marketplace_contract_z/Dashboard\n1\nMarketplace\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\naccept_offer_script\nbatch_buy_script\nbatch_delist_script\nbatch_list_script\nbid_script\ncancel_offer_script\nchange_token_price_script\nclaim_auction_coin_script\nclaim_auction_token_script\nclaim_offer_token_script\ninitial_auction_script\ninitial_market_script\nmake_offer_script\naccept_offer_script\nparam1\nparam2\nparam3\nparam4\nparam5\nTransact\noutputs\ncopy'
2023-09-22 15:13:05,011 - [test_contract_aptos.py - 187] - ERROR:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_marketplace_contract_z/Dashboard\n1\nMarketplace\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\naccept_offer_script\nbatch_buy_script\nbatch_delist_script\nbatch_list_script\nbid_script\ncancel_offer_script\nchange_token_price_script\nclaim_auction_coin_script\nclaim_auction_token_script\nclaim_offer_token_script\ninitial_auction_script\ninitial_market_script\nmake_offer_script\naccept_offer_script\nparam1\nparam2\nparam3\nparam4\nparam5\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_marketplace_contract_z/Dashboard\n1\nMarketplace\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\naccept_offer_script\nbatch_buy_script\nbatch_delist_script\nbatch_list_script\nbid_script\ncancel_offer_script\nchange_token_price_script\nclaim_auction_coin_script\nclaim_auction_token_script\nclaim_offer_token_script\ninitial_auction_script\ninitial_market_script\nmake_offer_script\naccept_offer_script\nparam1\nparam2\nparam3\nparam4\nparam5\nTransact\noutputs\ncopy'
2023-09-22 15:13:05,011 - [test_contract_aptos.py - 187] - ERROR:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_marketplace_contract_z/Dashboard\n1\nMarketplace\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\naccept_offer_script\nbatch_buy_script\nbatch_delist_script\nbatch_list_script\nbid_script\ncancel_offer_script\nchange_token_price_script\nclaim_auction_coin_script\nclaim_auction_token_script\nclaim_offer_token_script\ninitial_auction_script\ninitial_market_script\nmake_offer_script\naccept_offer_script\nparam1\nparam2\nparam3\nparam4\nparam5\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_marketplace_contract_z/Dashboard\n1\nMarketplace\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\naccept_offer_script\nbatch_buy_script\nbatch_delist_script\nbatch_list_script\nbid_script\ncancel_offer_script\nchange_token_price_script\nclaim_auction_coin_script\nclaim_auction_token_script\nclaim_offer_token_script\ninitial_auction_script\ninitial_market_script\nmake_offer_script\naccept_offer_script\nparam1\nparam2\nparam3\nparam4\nparam5\nTransact\noutputs\ncopy'
2023-09-22 15:13:05,011 - [test_contract_aptos.py - 187] - ERROR:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_marketplace_contract_z/Dashboard\n1\nMarketplace\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\naccept_offer_script\nbatch_buy_script\nbatch_delist_script\nbatch_list_script\nbid_script\ncancel_offer_script\nchange_token_price_script\nclaim_auction_coin_script\nclaim_auction_token_script\nclaim_offer_token_script\ninitial_auction_script\ninitial_market_script\nmake_offer_script\naccept_offer_script\nparam1\nparam2\nparam3\nparam4\nparam5\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_marketplace_contract_z/Dashboard\n1\nMarketplace\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\naccept_offer_script\nbatch_buy_script\nbatch_delist_script\nbatch_list_script\nbid_script\ncancel_offer_script\nchange_token_price_script\nclaim_auction_coin_script\nclaim_auction_token_script\nclaim_offer_token_script\ninitial_auction_script\ninitial_market_script\nmake_offer_script\naccept_offer_script\nparam1\nparam2\nparam3\nparam4\nparam5\nTransact\noutputs\ncopy'
2023-09-22 15:13:05,011 - [test_contract_aptos.py - 187] - ERROR:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_marketplace_contract_z/Dashboard\n1\nMarketplace\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\naccept_offer_script\nbatch_buy_script\nbatch_delist_script\nbatch_list_script\nbid_script\ncancel_offer_script\nchange_token_price_script\nclaim_auction_coin_script\nclaim_auction_token_script\nclaim_offer_token_script\ninitial_auction_script\ninitial_market_script\nmake_offer_script\naccept_offer_script\nparam1\nparam2\nparam3\nparam4\nparam5\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_marketplace_contract_z/Dashboard\n1\nMarketplace\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\naccept_offer_script\nbatch_buy_script\nbatch_delist_script\nbatch_list_script\nbid_script\ncancel_offer_script\nchange_token_price_script\nclaim_auction_coin_script\nclaim_auction_token_script\nclaim_offer_token_script\ninitial_auction_script\ninitial_market_script\nmake_offer_script\naccept_offer_script\nparam1\nparam2\nparam3\nparam4\nparam5\nTransact\noutputs\ncopy'
2023-09-22 15:13:52,165 - [test_contract_aptos.py - 186] - ERROR:测试编号:6,测试标题:['创建项目aptos_NFT_marketplace', '检查项目aptos_NFT_marketplace', '构建项目aptos_NFT_marketplace', '部署项目aptos_NFT_marketplace', '删除项目aptos_NFT_marketplace'],执行失败!实际结果:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_NFT_marketplace_z/Dashboard\n1\nmarketplace\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nbuy_token\ncreate_market\nlist_token\nbuy_token\nparam1\nparam2\nparam3\nparam4\nparam5\nparam6\nparam7\nparam8\nTransact\noutputs\ncopy'
2023-09-22 15:13:52,165 - [test_contract_aptos.py - 186] - ERROR:测试编号:6,测试标题:['创建项目aptos_NFT_marketplace', '检查项目aptos_NFT_marketplace', '构建项目aptos_NFT_marketplace', '部署项目aptos_NFT_marketplace', '删除项目aptos_NFT_marketplace'],执行失败!实际结果:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_NFT_marketplace_z/Dashboard\n1\nmarketplace\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nbuy_token\ncreate_market\nlist_token\nbuy_token\nparam1\nparam2\nparam3\nparam4\nparam5\nparam6\nparam7\nparam8\nTransact\noutputs\ncopy'
2023-09-22 15:13:52,165 - [test_contract_aptos.py - 186] - ERROR:测试编号:6,测试标题:['创建项目aptos_NFT_marketplace', '检查项目aptos_NFT_marketplace', '构建项目aptos_NFT_marketplace', '部署项目aptos_NFT_marketplace', '删除项目aptos_NFT_marketplace'],执行失败!实际结果:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_NFT_marketplace_z/Dashboard\n1\nmarketplace\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nbuy_token\ncreate_market\nlist_token\nbuy_token\nparam1\nparam2\nparam3\nparam4\nparam5\nparam6\nparam7\nparam8\nTransact\noutputs\ncopy'
2023-09-22 15:13:52,165 - [test_contract_aptos.py - 186] - ERROR:测试编号:6,测试标题:['创建项目aptos_NFT_marketplace', '检查项目aptos_NFT_marketplace', '构建项目aptos_NFT_marketplace', '部署项目aptos_NFT_marketplace', '删除项目aptos_NFT_marketplace'],执行失败!实际结果:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_NFT_marketplace_z/Dashboard\n1\nmarketplace\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nbuy_token\ncreate_market\nlist_token\nbuy_token\nparam1\nparam2\nparam3\nparam4\nparam5\nparam6\nparam7\nparam8\nTransact\noutputs\ncopy'
2023-09-22 15:13:52,167 - [test_contract_aptos.py - 187] - ERROR:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_NFT_marketplace_z/Dashboard\n1\nmarketplace\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nbuy_token\ncreate_market\nlist_token\nbuy_token\nparam1\nparam2\nparam3\nparam4\nparam5\nparam6\nparam7\nparam8\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_NFT_marketplace_z/Dashboard\n1\nmarketplace\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nbuy_token\ncreate_market\nlist_token\nbuy_token\nparam1\nparam2\nparam3\nparam4\nparam5\nparam6\nparam7\nparam8\nTransact\noutputs\ncopy'
2023-09-22 15:13:52,167 - [test_contract_aptos.py - 187] - ERROR:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_NFT_marketplace_z/Dashboard\n1\nmarketplace\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nbuy_token\ncreate_market\nlist_token\nbuy_token\nparam1\nparam2\nparam3\nparam4\nparam5\nparam6\nparam7\nparam8\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_NFT_marketplace_z/Dashboard\n1\nmarketplace\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nbuy_token\ncreate_market\nlist_token\nbuy_token\nparam1\nparam2\nparam3\nparam4\nparam5\nparam6\nparam7\nparam8\nTransact\noutputs\ncopy'
2023-09-22 15:13:52,167 - [test_contract_aptos.py - 187] - ERROR:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_NFT_marketplace_z/Dashboard\n1\nmarketplace\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nbuy_token\ncreate_market\nlist_token\nbuy_token\nparam1\nparam2\nparam3\nparam4\nparam5\nparam6\nparam7\nparam8\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_NFT_marketplace_z/Dashboard\n1\nmarketplace\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nbuy_token\ncreate_market\nlist_token\nbuy_token\nparam1\nparam2\nparam3\nparam4\nparam5\nparam6\nparam7\nparam8\nTransact\noutputs\ncopy'
2023-09-22 15:13:52,167 - [test_contract_aptos.py - 187] - ERROR:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_NFT_marketplace_z/Dashboard\n1\nmarketplace\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nbuy_token\ncreate_market\nlist_token\nbuy_token\nparam1\nparam2\nparam3\nparam4\nparam5\nparam6\nparam7\nparam8\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_NFT_marketplace_z/Dashboard\n1\nmarketplace\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nbuy_token\ncreate_market\nlist_token\nbuy_token\nparam1\nparam2\nparam3\nparam4\nparam5\nparam6\nparam7\nparam8\nTransact\noutputs\ncopy'
2023-09-22 15:14:57,651 - [test_contract_aptos.py - 186] - ERROR:测试编号:7,测试标题:['创建项目aptos_raffle', '检查项目aptos_raffle', '构建项目aptos_raffle', '部署项目aptos_raffle', '删除项目aptos_raffle'],执行失败!实际结果:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_raffle_z/Dashboard\n1\nraffle\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncheck_claim_reward\ndeclare_winner\nplay_raffle\nstart_raffle\ncheck_claim_reward\nparam1\nparam2\nTransact\noutputs\ncopy'
2023-09-22 15:14:57,651 - [test_contract_aptos.py - 186] - ERROR:测试编号:7,测试标题:['创建项目aptos_raffle', '检查项目aptos_raffle', '构建项目aptos_raffle', '部署项目aptos_raffle', '删除项目aptos_raffle'],执行失败!实际结果:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_raffle_z/Dashboard\n1\nraffle\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncheck_claim_reward\ndeclare_winner\nplay_raffle\nstart_raffle\ncheck_claim_reward\nparam1\nparam2\nTransact\noutputs\ncopy'
2023-09-22 15:14:57,651 - [test_contract_aptos.py - 186] - ERROR:测试编号:7,测试标题:['创建项目aptos_raffle', '检查项目aptos_raffle', '构建项目aptos_raffle', '部署项目aptos_raffle', '删除项目aptos_raffle'],执行失败!实际结果:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_raffle_z/Dashboard\n1\nraffle\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncheck_claim_reward\ndeclare_winner\nplay_raffle\nstart_raffle\ncheck_claim_reward\nparam1\nparam2\nTransact\noutputs\ncopy'
2023-09-22 15:14:57,651 - [test_contract_aptos.py - 186] - ERROR:测试编号:7,测试标题:['创建项目aptos_raffle', '检查项目aptos_raffle', '构建项目aptos_raffle', '部署项目aptos_raffle', '删除项目aptos_raffle'],执行失败!实际结果:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_raffle_z/Dashboard\n1\nraffle\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncheck_claim_reward\ndeclare_winner\nplay_raffle\nstart_raffle\ncheck_claim_reward\nparam1\nparam2\nTransact\noutputs\ncopy'
2023-09-22 15:14:57,653 - [test_contract_aptos.py - 187] - ERROR:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_raffle_z/Dashboard\n1\nraffle\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncheck_claim_reward\ndeclare_winner\nplay_raffle\nstart_raffle\ncheck_claim_reward\nparam1\nparam2\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_raffle_z/Dashboard\n1\nraffle\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncheck_claim_reward\ndeclare_winner\nplay_raffle\nstart_raffle\ncheck_claim_reward\nparam1\nparam2\nTransact\noutputs\ncopy'
2023-09-22 15:14:57,653 - [test_contract_aptos.py - 187] - ERROR:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_raffle_z/Dashboard\n1\nraffle\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncheck_claim_reward\ndeclare_winner\nplay_raffle\nstart_raffle\ncheck_claim_reward\nparam1\nparam2\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_raffle_z/Dashboard\n1\nraffle\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncheck_claim_reward\ndeclare_winner\nplay_raffle\nstart_raffle\ncheck_claim_reward\nparam1\nparam2\nTransact\noutputs\ncopy'
2023-09-22 15:14:57,653 - [test_contract_aptos.py - 187] - ERROR:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_raffle_z/Dashboard\n1\nraffle\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncheck_claim_reward\ndeclare_winner\nplay_raffle\nstart_raffle\ncheck_claim_reward\nparam1\nparam2\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_raffle_z/Dashboard\n1\nraffle\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncheck_claim_reward\ndeclare_winner\nplay_raffle\nstart_raffle\ncheck_claim_reward\nparam1\nparam2\nTransact\noutputs\ncopy'
2023-09-22 15:14:57,653 - [test_contract_aptos.py - 187] - ERROR:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_raffle_z/Dashboard\n1\nraffle\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncheck_claim_reward\ndeclare_winner\nplay_raffle\nstart_raffle\ncheck_claim_reward\nparam1\nparam2\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_raffle_z/Dashboard\n1\nraffle\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncheck_claim_reward\ndeclare_winner\nplay_raffle\nstart_raffle\ncheck_claim_reward\nparam1\nparam2\nTransact\noutputs\ncopy'
2023-09-22 15:15:41,460 - [test_contract_aptos.py - 186] - ERROR:测试编号:8,测试标题:['创建项目aptos_candymachine', '检查项目aptos_candymachine', '构建项目aptos_candymachine', '部署项目aptos_candymachine', '删除项目aptos_candymachine'],执行失败!实际结果:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_candymachine_z/Dashboard\n1\ncandymachine\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncreate_whitelist\nmint_script\nmutate_one_token\nmutate_tokendata_property\nmutate_tokendata_uri\npause_mint\nresume_mint\nset_up_candy\nupdate_candy\ncreate_whitelist\nparam1\nparam2\nparam3\nTransact\noutputs\ncopy'
2023-09-22 15:15:41,460 - [test_contract_aptos.py - 186] - ERROR:测试编号:8,测试标题:['创建项目aptos_candymachine', '检查项目aptos_candymachine', '构建项目aptos_candymachine', '部署项目aptos_candymachine', '删除项目aptos_candymachine'],执行失败!实际结果:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_candymachine_z/Dashboard\n1\ncandymachine\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncreate_whitelist\nmint_script\nmutate_one_token\nmutate_tokendata_property\nmutate_tokendata_uri\npause_mint\nresume_mint\nset_up_candy\nupdate_candy\ncreate_whitelist\nparam1\nparam2\nparam3\nTransact\noutputs\ncopy'
2023-09-22 15:15:41,460 - [test_contract_aptos.py - 186] - ERROR:测试编号:8,测试标题:['创建项目aptos_candymachine', '检查项目aptos_candymachine', '构建项目aptos_candymachine', '部署项目aptos_candymachine', '删除项目aptos_candymachine'],执行失败!实际结果:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_candymachine_z/Dashboard\n1\ncandymachine\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncreate_whitelist\nmint_script\nmutate_one_token\nmutate_tokendata_property\nmutate_tokendata_uri\npause_mint\nresume_mint\nset_up_candy\nupdate_candy\ncreate_whitelist\nparam1\nparam2\nparam3\nTransact\noutputs\ncopy'
2023-09-22 15:15:41,460 - [test_contract_aptos.py - 186] - ERROR:测试编号:8,测试标题:['创建项目aptos_candymachine', '检查项目aptos_candymachine', '构建项目aptos_candymachine', '部署项目aptos_candymachine', '删除项目aptos_candymachine'],执行失败!实际结果:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_candymachine_z/Dashboard\n1\ncandymachine\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncreate_whitelist\nmint_script\nmutate_one_token\nmutate_tokendata_property\nmutate_tokendata_uri\npause_mint\nresume_mint\nset_up_candy\nupdate_candy\ncreate_whitelist\nparam1\nparam2\nparam3\nTransact\noutputs\ncopy'
2023-09-22 15:15:41,462 - [test_contract_aptos.py - 187] - ERROR:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_candymachine_z/Dashboard\n1\ncandymachine\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncreate_whitelist\nmint_script\nmutate_one_token\nmutate_tokendata_property\nmutate_tokendata_uri\npause_mint\nresume_mint\nset_up_candy\nupdate_candy\ncreate_whitelist\nparam1\nparam2\nparam3\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_candymachine_z/Dashboard\n1\ncandymachine\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncreate_whitelist\nmint_script\nmutate_one_token\nmutate_tokendata_property\nmutate_tokendata_uri\npause_mint\nresume_mint\nset_up_candy\nupdate_candy\ncreate_whitelist\nparam1\nparam2\nparam3\nTransact\noutputs\ncopy'
2023-09-22 15:15:41,462 - [test_contract_aptos.py - 187] - ERROR:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_candymachine_z/Dashboard\n1\ncandymachine\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncreate_whitelist\nmint_script\nmutate_one_token\nmutate_tokendata_property\nmutate_tokendata_uri\npause_mint\nresume_mint\nset_up_candy\nupdate_candy\ncreate_whitelist\nparam1\nparam2\nparam3\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_candymachine_z/Dashboard\n1\ncandymachine\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncreate_whitelist\nmint_script\nmutate_one_token\nmutate_tokendata_property\nmutate_tokendata_uri\npause_mint\nresume_mint\nset_up_candy\nupdate_candy\ncreate_whitelist\nparam1\nparam2\nparam3\nTransact\noutputs\ncopy'
2023-09-22 15:15:41,462 - [test_contract_aptos.py - 187] - ERROR:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_candymachine_z/Dashboard\n1\ncandymachine\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncreate_whitelist\nmint_script\nmutate_one_token\nmutate_tokendata_property\nmutate_tokendata_uri\npause_mint\nresume_mint\nset_up_candy\nupdate_candy\ncreate_whitelist\nparam1\nparam2\nparam3\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_candymachine_z/Dashboard\n1\ncandymachine\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncreate_whitelist\nmint_script\nmutate_one_token\nmutate_tokendata_property\nmutate_tokendata_uri\npause_mint\nresume_mint\nset_up_candy\nupdate_candy\ncreate_whitelist\nparam1\nparam2\nparam3\nTransact\noutputs\ncopy'
2023-09-22 15:15:41,462 - [test_contract_aptos.py - 187] - ERROR:assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_candymachine_z/Dashboard\n1\ncandymachine\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncreate_whitelist\nmint_script\nmutate_one_token\nmutate_tokendata_property\nmutate_tokendata_uri\npause_mint\nresume_mint\nset_up_candy\nupdate_candy\ncreate_whitelist\nparam1\nparam2\nparam3\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'Call' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_candymachine_z/Dashboard\n1\ncandymachine\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ncreate_whitelist\nmint_script\nmutate_one_token\nmutate_tokendata_property\nmutate_tokendata_uri\npause_mint\nresume_mint\nset_up_candy\nupdate_candy\ncreate_whitelist\nparam1\nparam2\nparam3\nTransact\noutputs\ncopy'
2023-09-22 15:16:28,295 - [test_contract_aptos.py - 183] - INFO:测试编号:9,测试标题:部署项目aptos_merkproof,执行成功！
2023-09-22 15:16:28,295 - [test_contract_aptos.py - 183] - INFO:测试编号:9,测试标题:部署项目aptos_merkproof,执行成功！
2023-09-22 15:16:28,295 - [test_contract_aptos.py - 183] - INFO:测试编号:9,测试标题:部署项目aptos_merkproof,执行成功！
2023-09-22 15:16:28,295 - [test_contract_aptos.py - 183] - INFO:测试编号:9,测试标题:部署项目aptos_merkproof,执行成功！
2023-09-22 15:17:15,854 - [test_contract_aptos.py - 186] - ERROR:测试编号:10,测试标题:['创建项目aptos_hello_blockchain', '检查项目aptos_hello_blockchain', '构建项目aptos_hello_blockchain', '部署项目aptos_hello_blockchain', '删除项目aptos_hello_blockchain'],执行失败!实际结果:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_hello_blockchain_z/Dashboard\n1\nmessage\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nget_message\nset_message\nget_message\nparam1\nTransact\noutputs\ncopy'
2023-09-22 15:17:15,854 - [test_contract_aptos.py - 186] - ERROR:测试编号:10,测试标题:['创建项目aptos_hello_blockchain', '检查项目aptos_hello_blockchain', '构建项目aptos_hello_blockchain', '部署项目aptos_hello_blockchain', '删除项目aptos_hello_blockchain'],执行失败!实际结果:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_hello_blockchain_z/Dashboard\n1\nmessage\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nget_message\nset_message\nget_message\nparam1\nTransact\noutputs\ncopy'
2023-09-22 15:17:15,854 - [test_contract_aptos.py - 186] - ERROR:测试编号:10,测试标题:['创建项目aptos_hello_blockchain', '检查项目aptos_hello_blockchain', '构建项目aptos_hello_blockchain', '部署项目aptos_hello_blockchain', '删除项目aptos_hello_blockchain'],执行失败!实际结果:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_hello_blockchain_z/Dashboard\n1\nmessage\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nget_message\nset_message\nget_message\nparam1\nTransact\noutputs\ncopy'
2023-09-22 15:17:15,854 - [test_contract_aptos.py - 186] - ERROR:测试编号:10,测试标题:['创建项目aptos_hello_blockchain', '检查项目aptos_hello_blockchain', '构建项目aptos_hello_blockchain', '部署项目aptos_hello_blockchain', '删除项目aptos_hello_blockchain'],执行失败!实际结果:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_hello_blockchain_z/Dashboard\n1\nmessage\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nget_message\nset_message\nget_message\nparam1\nTransact\noutputs\ncopy'
2023-09-22 15:17:15,857 - [test_contract_aptos.py - 187] - ERROR:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_hello_blockchain_z/Dashboard\n1\nmessage\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nget_message\nset_message\nget_message\nparam1\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_hello_blockchain_z/Dashboard\n1\nmessage\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nget_message\nset_message\nget_message\nparam1\nTransact\noutputs\ncopy'
2023-09-22 15:17:15,857 - [test_contract_aptos.py - 187] - ERROR:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_hello_blockchain_z/Dashboard\n1\nmessage\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nget_message\nset_message\nget_message\nparam1\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_hello_blockchain_z/Dashboard\n1\nmessage\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nget_message\nset_message\nget_message\nparam1\nTransact\noutputs\ncopy'
2023-09-22 15:17:15,857 - [test_contract_aptos.py - 187] - ERROR:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_hello_blockchain_z/Dashboard\n1\nmessage\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nget_message\nset_message\nget_message\nparam1\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_hello_blockchain_z/Dashboard\n1\nmessage\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nget_message\nset_message\nget_message\nparam1\nTransact\noutputs\ncopy'
2023-09-22 15:17:15,857 - [test_contract_aptos.py - 187] - ERROR:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_hello_blockchain_z/Dashboard\n1\nmessage\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nget_message\nset_message\nget_message\nparam1\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_hello_blockchain_z/Dashboard\n1\nmessage\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nget_message\nset_message\nget_message\nparam1\nTransact\noutputs\ncopy'
2023-09-22 15:17:59,578 - [test_contract_aptos.py - 186] - ERROR:测试编号:11,测试标题:['创建项目aptos_warkade', '检查项目aptos_warkade', '构建项目aptos_warkade', '部署项目aptos_warkade', '删除项目aptos_warkade'],执行失败!实际结果:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_warkade_z/Dashboard\n1\nwarkade\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nadd_layer\ndeposit\ninitiate_collection\ninitiate_layers\nmint\nmints_remain\nupdate_price\nupdate_royalty\nupdate_uri\nadd_layer\nparam1\nparam2\nTransact\noutputs\ncopy'
2023-09-22 15:17:59,578 - [test_contract_aptos.py - 186] - ERROR:测试编号:11,测试标题:['创建项目aptos_warkade', '检查项目aptos_warkade', '构建项目aptos_warkade', '部署项目aptos_warkade', '删除项目aptos_warkade'],执行失败!实际结果:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_warkade_z/Dashboard\n1\nwarkade\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nadd_layer\ndeposit\ninitiate_collection\ninitiate_layers\nmint\nmints_remain\nupdate_price\nupdate_royalty\nupdate_uri\nadd_layer\nparam1\nparam2\nTransact\noutputs\ncopy'
2023-09-22 15:17:59,578 - [test_contract_aptos.py - 186] - ERROR:测试编号:11,测试标题:['创建项目aptos_warkade', '检查项目aptos_warkade', '构建项目aptos_warkade', '部署项目aptos_warkade', '删除项目aptos_warkade'],执行失败!实际结果:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_warkade_z/Dashboard\n1\nwarkade\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nadd_layer\ndeposit\ninitiate_collection\ninitiate_layers\nmint\nmints_remain\nupdate_price\nupdate_royalty\nupdate_uri\nadd_layer\nparam1\nparam2\nTransact\noutputs\ncopy'
2023-09-22 15:17:59,578 - [test_contract_aptos.py - 186] - ERROR:测试编号:11,测试标题:['创建项目aptos_warkade', '检查项目aptos_warkade', '构建项目aptos_warkade', '部署项目aptos_warkade', '删除项目aptos_warkade'],执行失败!实际结果:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_warkade_z/Dashboard\n1\nwarkade\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nadd_layer\ndeposit\ninitiate_collection\ninitiate_layers\nmint\nmints_remain\nupdate_price\nupdate_royalty\nupdate_uri\nadd_layer\nparam1\nparam2\nTransact\noutputs\ncopy'
2023-09-22 15:17:59,580 - [test_contract_aptos.py - 187] - ERROR:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_warkade_z/Dashboard\n1\nwarkade\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nadd_layer\ndeposit\ninitiate_collection\ninitiate_layers\nmint\nmints_remain\nupdate_price\nupdate_royalty\nupdate_uri\nadd_layer\nparam1\nparam2\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_warkade_z/Dashboard\n1\nwarkade\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nadd_layer\ndeposit\ninitiate_collection\ninitiate_layers\nmint\nmints_remain\nupdate_price\nupdate_royalty\nupdate_uri\nadd_layer\nparam1\nparam2\nTransact\noutputs\ncopy'
2023-09-22 15:17:59,580 - [test_contract_aptos.py - 187] - ERROR:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_warkade_z/Dashboard\n1\nwarkade\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nadd_layer\ndeposit\ninitiate_collection\ninitiate_layers\nmint\nmints_remain\nupdate_price\nupdate_royalty\nupdate_uri\nadd_layer\nparam1\nparam2\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_warkade_z/Dashboard\n1\nwarkade\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nadd_layer\ndeposit\ninitiate_collection\ninitiate_layers\nmint\nmints_remain\nupdate_price\nupdate_royalty\nupdate_uri\nadd_layer\nparam1\nparam2\nTransact\noutputs\ncopy'
2023-09-22 15:17:59,580 - [test_contract_aptos.py - 187] - ERROR:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_warkade_z/Dashboard\n1\nwarkade\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nadd_layer\ndeposit\ninitiate_collection\ninitiate_layers\nmint\nmints_remain\nupdate_price\nupdate_royalty\nupdate_uri\nadd_layer\nparam1\nparam2\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_warkade_z/Dashboard\n1\nwarkade\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nadd_layer\ndeposit\ninitiate_collection\ninitiate_layers\nmint\nmints_remain\nupdate_price\nupdate_royalty\nupdate_uri\nadd_layer\nparam1\nparam2\nTransact\noutputs\ncopy'
2023-09-22 15:17:59,580 - [test_contract_aptos.py - 187] - ERROR:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_warkade_z/Dashboard\n1\nwarkade\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nadd_layer\ndeposit\ninitiate_collection\ninitiate_layers\nmint\nmints_remain\nupdate_price\nupdate_royalty\nupdate_uri\nadd_layer\nparam1\nparam2\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_warkade_z/Dashboard\n1\nwarkade\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\nadd_layer\ndeposit\ninitiate_collection\ninitiate_layers\nmint\nmints_remain\nupdate_price\nupdate_royalty\nupdate_uri\nadd_layer\nparam1\nparam2\nTransact\noutputs\ncopy'
2023-09-22 15:18:46,654 - [test_contract_aptos.py - 186] - ERROR:测试编号:12,测试标题:['创建项目aptos_tokenv2_wrapper', '检查项目aptos_tokenv2_wrapper', '构建项目aptos_tokenv2_wrapper', '部署项目aptos_tokenv2_wrapper', '删除项目aptos_tokenv2_wrapper'],执行失败!实际结果:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_tokenv2_wrapper_z/Dashboard\n1\nwrapper\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ninitiate_collection\nwrap_obj_address\nwrap_token\ninitiate_collection\nparam1\nparam2\nparam3\nparam4\nTransact\noutputs\ncopy'
2023-09-22 15:18:46,654 - [test_contract_aptos.py - 186] - ERROR:测试编号:12,测试标题:['创建项目aptos_tokenv2_wrapper', '检查项目aptos_tokenv2_wrapper', '构建项目aptos_tokenv2_wrapper', '部署项目aptos_tokenv2_wrapper', '删除项目aptos_tokenv2_wrapper'],执行失败!实际结果:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_tokenv2_wrapper_z/Dashboard\n1\nwrapper\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ninitiate_collection\nwrap_obj_address\nwrap_token\ninitiate_collection\nparam1\nparam2\nparam3\nparam4\nTransact\noutputs\ncopy'
2023-09-22 15:18:46,654 - [test_contract_aptos.py - 186] - ERROR:测试编号:12,测试标题:['创建项目aptos_tokenv2_wrapper', '检查项目aptos_tokenv2_wrapper', '构建项目aptos_tokenv2_wrapper', '部署项目aptos_tokenv2_wrapper', '删除项目aptos_tokenv2_wrapper'],执行失败!实际结果:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_tokenv2_wrapper_z/Dashboard\n1\nwrapper\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ninitiate_collection\nwrap_obj_address\nwrap_token\ninitiate_collection\nparam1\nparam2\nparam3\nparam4\nTransact\noutputs\ncopy'
2023-09-22 15:18:46,654 - [test_contract_aptos.py - 186] - ERROR:测试编号:12,测试标题:['创建项目aptos_tokenv2_wrapper', '检查项目aptos_tokenv2_wrapper', '构建项目aptos_tokenv2_wrapper', '部署项目aptos_tokenv2_wrapper', '删除项目aptos_tokenv2_wrapper'],执行失败!实际结果:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_tokenv2_wrapper_z/Dashboard\n1\nwrapper\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ninitiate_collection\nwrap_obj_address\nwrap_token\ninitiate_collection\nparam1\nparam2\nparam3\nparam4\nTransact\noutputs\ncopy'
2023-09-22 15:18:46,655 - [test_contract_aptos.py - 187] - ERROR:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_tokenv2_wrapper_z/Dashboard\n1\nwrapper\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ninitiate_collection\nwrap_obj_address\nwrap_token\ninitiate_collection\nparam1\nparam2\nparam3\nparam4\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_tokenv2_wrapper_z/Dashboard\n1\nwrapper\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ninitiate_collection\nwrap_obj_address\nwrap_token\ninitiate_collection\nparam1\nparam2\nparam3\nparam4\nTransact\noutputs\ncopy'
2023-09-22 15:18:46,655 - [test_contract_aptos.py - 187] - ERROR:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_tokenv2_wrapper_z/Dashboard\n1\nwrapper\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ninitiate_collection\nwrap_obj_address\nwrap_token\ninitiate_collection\nparam1\nparam2\nparam3\nparam4\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_tokenv2_wrapper_z/Dashboard\n1\nwrapper\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ninitiate_collection\nwrap_obj_address\nwrap_token\ninitiate_collection\nparam1\nparam2\nparam3\nparam4\nTransact\noutputs\ncopy'
2023-09-22 15:18:46,655 - [test_contract_aptos.py - 187] - ERROR:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_tokenv2_wrapper_z/Dashboard\n1\nwrapper\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ninitiate_collection\nwrap_obj_address\nwrap_token\ninitiate_collection\nparam1\nparam2\nparam3\nparam4\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_tokenv2_wrapper_z/Dashboard\n1\nwrapper\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ninitiate_collection\nwrap_obj_address\nwrap_token\ninitiate_collection\nparam1\nparam2\nparam3\nparam4\nTransact\noutputs\ncopy'
2023-09-22 15:18:46,655 - [test_contract_aptos.py - 187] - ERROR:assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_tokenv2_wrapper_z/Dashboard\n1\nwrapper\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ninitiate_collection\nwrap_obj_address\nwrap_token\ninitiate_collection\nparam1\nparam2\nparam3\nparam4\nTransact\noutputs\ncopy'
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\work_space\BaiduSyncdisk\auto_test\hamster_test\test_cases\test_contract\test_contract_aptos.py", line 181, in test_deploy
    assert case['text']['tx6'] in tx
AssertionError: assert 'verify' in 'Projects\nMiddleware\nDocs\nEthereum Mainnet\n0x156...e010\nProjects/Contract_aptos_tokenv2_wrapper_z/Dashboard\n1\nwrapper\nNetwork Address Action\nTestnet 0x5fb889ec5490c7660d90fe48fe06f5e5e3a367dd0b650b62e6e54123e84f4b06 Deploy\nContract List\nSend\ninitiate_collection\nwrap_obj_address\nwrap_token\ninitiate_collection\nparam1\nparam2\nparam3\nparam4\nTransact\noutputs\ncopy'
2023-09-22 15:19:10,870 - [opject.py - 88] - ERROR:a[href="/daixiang11/Contract_aptos_staking_z/settings"]元素点击失败
2023-09-22 15:19:10,870 - [opject.py - 88] - ERROR:a[href="/daixiang11/Contract_aptos_staking_z/settings"]元素点击失败
2023-09-22 15:19:10,870 - [opject.py - 88] - ERROR:a[href="/daixiang11/Contract_aptos_staking_z/settings"]元素点击失败
2023-09-22 15:19:10,870 - [opject.py - 88] - ERROR:a[href="/daixiang11/Contract_aptos_staking_z/settings"]元素点击失败
2023-09-22 15:19:10,870 - [opject.py - 88] - ERROR:a[href="/daixiang11/Contract_aptos_staking_z/settings"]元素点击失败
2023-09-22 15:19:38,633 - [opject.py - 88] - ERROR:a[href="/daixiang11/Contract_aptos_westing_z/settings"]元素点击失败
2023-09-22 15:19:38,633 - [opject.py - 88] - ERROR:a[href="/daixiang11/Contract_aptos_westing_z/settings"]元素点击失败
2023-09-22 15:19:38,633 - [opject.py - 88] - ERROR:a[href="/daixiang11/Contract_aptos_westing_z/settings"]元素点击失败
2023-09-22 15:19:38,633 - [opject.py - 88] - ERROR:a[href="/daixiang11/Contract_aptos_westing_z/settings"]元素点击失败
2023-09-22 15:19:38,633 - [opject.py - 88] - ERROR:a[href="/daixiang11/Contract_aptos_westing_z/settings"]元素点击失败
2023-09-22 15:19:38,633 - [opject.py - 88] - ERROR:a[href="/daixiang11/Contract_aptos_westing_z/settings"]元素点击失败
2023-09-22 15:20:45,191 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020853399CA0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/3392a24372ab4111ed8ba16749d526ee
2023-09-22 15:20:45,191 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020853399CA0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/3392a24372ab4111ed8ba16749d526ee
2023-09-22 15:20:49,253 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020853F73160>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/3392a24372ab4111ed8ba16749d526ee
2023-09-22 15:20:49,253 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020853F73160>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/3392a24372ab4111ed8ba16749d526ee
2023-09-22 15:20:53,339 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020853F73220>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/3392a24372ab4111ed8ba16749d526ee
2023-09-22 15:20:53,339 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020853F73220>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/3392a24372ab4111ed8ba16749d526ee
2023-09-22 15:22:02,937 - [test_contract_aptos.py - 240] - INFO:测试编号:1,测试标题:['创建项目aptos_staking', '检查项目aptos_staking', '构建项目aptos_staking', '部署项目aptos_staking', '删除项目aptos_staking'],执行成功！
2023-09-22 15:22:02,937 - [test_contract_aptos.py - 240] - INFO:测试编号:1,测试标题:['创建项目aptos_staking', '检查项目aptos_staking', '构建项目aptos_staking', '部署项目aptos_staking', '删除项目aptos_staking'],执行成功！
2023-09-22 15:23:22,377 - [test_contract_aptos.py - 240] - INFO:测试编号:2,测试标题:['创建项目aptos_vesting', '检查项目aptos_westing', '构建项目aptos_westing', '部署项目aptos_westing', '删除项目aptos_westing'],执行成功！
2023-09-22 15:23:22,377 - [test_contract_aptos.py - 240] - INFO:测试编号:2,测试标题:['创建项目aptos_vesting', '检查项目aptos_westing', '构建项目aptos_westing', '部署项目aptos_westing', '删除项目aptos_westing'],执行成功！
2023-09-22 15:24:25,039 - [test_contract_aptos.py - 240] - INFO:测试编号:3,测试标题:['创建项目aptos_lending', '检查项目aptos_lending', '构建项目aptos_lending', '部署项目aptos_lending', '删除项目aptos_lending'],执行成功！
2023-09-22 15:24:25,039 - [test_contract_aptos.py - 240] - INFO:测试编号:3,测试标题:['创建项目aptos_lending', '检查项目aptos_lending', '构建项目aptos_lending', '部署项目aptos_lending', '删除项目aptos_lending'],执行成功！
2023-09-22 15:25:26,322 - [test_contract_aptos.py - 240] - INFO:测试编号:4,测试标题:['创建项目aptos_ToDoList', '检查项目aptos_ToDoList', '构建项目aptos_ToDoList', '部署项目aptos_ToDoList', '删除项目aptos_ToDoList'],执行成功！
2023-09-22 15:25:26,322 - [test_contract_aptos.py - 240] - INFO:测试编号:4,测试标题:['创建项目aptos_ToDoList', '检查项目aptos_ToDoList', '构建项目aptos_ToDoList', '部署项目aptos_ToDoList', '删除项目aptos_ToDoList'],执行成功！
2023-09-22 15:26:26,906 - [test_contract_aptos.py - 240] - INFO:测试编号:5,测试标题:['创建项目aptos_marketplace_contract', '检查项目aptos_marketplace_contract', '构建项目aptos_marketplace_contract', '部署项目aptos_marketplace_contract', '删除项目aptos_marketplace_contract'],执行成功！
2023-09-22 15:26:26,906 - [test_contract_aptos.py - 240] - INFO:测试编号:5,测试标题:['创建项目aptos_marketplace_contract', '检查项目aptos_marketplace_contract', '构建项目aptos_marketplace_contract', '部署项目aptos_marketplace_contract', '删除项目aptos_marketplace_contract'],执行成功！
2023-09-22 15:27:27,135 - [test_contract_aptos.py - 240] - INFO:测试编号:6,测试标题:['创建项目aptos_NFT_marketplace', '检查项目aptos_NFT_marketplace', '构建项目aptos_NFT_marketplace', '部署项目aptos_NFT_marketplace', '删除项目aptos_NFT_marketplace'],执行成功！
2023-09-22 15:27:27,135 - [test_contract_aptos.py - 240] - INFO:测试编号:6,测试标题:['创建项目aptos_NFT_marketplace', '检查项目aptos_NFT_marketplace', '构建项目aptos_NFT_marketplace', '部署项目aptos_NFT_marketplace', '删除项目aptos_NFT_marketplace'],执行成功！
2023-09-22 15:28:27,287 - [test_contract_aptos.py - 240] - INFO:测试编号:7,测试标题:['创建项目aptos_raffle', '检查项目aptos_raffle', '构建项目aptos_raffle', '部署项目aptos_raffle', '删除项目aptos_raffle'],执行成功！
2023-09-22 15:28:27,287 - [test_contract_aptos.py - 240] - INFO:测试编号:7,测试标题:['创建项目aptos_raffle', '检查项目aptos_raffle', '构建项目aptos_raffle', '部署项目aptos_raffle', '删除项目aptos_raffle'],执行成功！
2023-09-22 15:29:28,040 - [test_contract_aptos.py - 240] - INFO:测试编号:8,测试标题:['创建项目aptos_candymachine', '检查项目aptos_candymachine', '构建项目aptos_candymachine', '部署项目aptos_candymachine', '删除项目aptos_candymachine'],执行成功！
2023-09-22 15:29:28,040 - [test_contract_aptos.py - 240] - INFO:测试编号:8,测试标题:['创建项目aptos_candymachine', '检查项目aptos_candymachine', '构建项目aptos_candymachine', '部署项目aptos_candymachine', '删除项目aptos_candymachine'],执行成功！
2023-09-22 15:30:28,032 - [test_contract_aptos.py - 240] - INFO:测试编号:9,测试标题:['创建项目aptos_merkproof', '检查项目aptos_merkproof', '构建项目aptos_merkproof', '部署项目aptos_merkproof', '删除项目aptos_merkproof'],执行成功！
2023-09-22 15:30:28,032 - [test_contract_aptos.py - 240] - INFO:测试编号:9,测试标题:['创建项目aptos_merkproof', '检查项目aptos_merkproof', '构建项目aptos_merkproof', '部署项目aptos_merkproof', '删除项目aptos_merkproof'],执行成功！
2023-09-22 15:31:33,640 - [test_contract_aptos.py - 240] - INFO:测试编号:10,测试标题:['创建项目aptos_hello_blockchain', '检查项目aptos_hello_blockchain', '构建项目aptos_hello_blockchain', '部署项目aptos_hello_blockchain', '删除项目aptos_hello_blockchain'],执行成功！
2023-09-22 15:31:33,640 - [test_contract_aptos.py - 240] - INFO:测试编号:10,测试标题:['创建项目aptos_hello_blockchain', '检查项目aptos_hello_blockchain', '构建项目aptos_hello_blockchain', '部署项目aptos_hello_blockchain', '删除项目aptos_hello_blockchain'],执行成功！
2023-09-22 15:32:33,096 - [test_contract_aptos.py - 240] - INFO:测试编号:11,测试标题:['创建项目aptos_warkade', '检查项目aptos_warkade', '构建项目aptos_warkade', '部署项目aptos_warkade', '删除项目aptos_warkade'],执行成功！
2023-09-22 15:32:33,096 - [test_contract_aptos.py - 240] - INFO:测试编号:11,测试标题:['创建项目aptos_warkade', '检查项目aptos_warkade', '构建项目aptos_warkade', '部署项目aptos_warkade', '删除项目aptos_warkade'],执行成功！
2023-09-22 15:33:32,589 - [test_contract_aptos.py - 240] - INFO:测试编号:12,测试标题:['创建项目aptos_tokenv2_wrapper', '检查项目aptos_tokenv2_wrapper', '构建项目aptos_tokenv2_wrapper', '部署项目aptos_tokenv2_wrapper', '删除项目aptos_tokenv2_wrapper'],执行成功！
2023-09-22 15:33:32,589 - [test_contract_aptos.py - 240] - INFO:测试编号:12,测试标题:['创建项目aptos_tokenv2_wrapper', '检查项目aptos_tokenv2_wrapper', '构建项目aptos_tokenv2_wrapper', '部署项目aptos_tokenv2_wrapper', '删除项目aptos_tokenv2_wrapper'],执行成功！
2023-09-22 16:49:35,591 - [opject.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-09-22 16:49:35,591 - [opject.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-09-22 16:49:35,591 - [opject.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-09-22 16:56:01,777 - [opject.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-09-22 16:56:01,777 - [opject.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-09-22 16:56:01,777 - [opject.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-09-22 16:56:33,247 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F784BF4F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/67ec7c64b9cca7eceff038b053bdca7f
2023-09-22 16:56:33,247 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F784BF4F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/67ec7c64b9cca7eceff038b053bdca7f
2023-09-22 16:56:33,247 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F784BF4F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/67ec7c64b9cca7eceff038b053bdca7f
2023-09-22 16:56:37,356 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F78E6E040>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/67ec7c64b9cca7eceff038b053bdca7f
2023-09-22 16:56:37,356 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F78E6E040>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/67ec7c64b9cca7eceff038b053bdca7f
2023-09-22 16:56:37,356 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F78E6E040>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/67ec7c64b9cca7eceff038b053bdca7f
2023-09-22 16:56:41,438 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F78E6EEE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/67ec7c64b9cca7eceff038b053bdca7f
2023-09-22 16:56:41,438 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F78E6EEE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/67ec7c64b9cca7eceff038b053bdca7f
2023-09-22 16:56:41,438 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F78E6EEE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/67ec7c64b9cca7eceff038b053bdca7f
2023-09-22 17:04:37,380 - [opject.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[1]/div[2]/button[3]元素点击失败
2023-09-22 17:04:37,380 - [opject.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[1]/div[2]/button[3]元素点击失败
2023-09-22 17:04:37,380 - [opject.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[1]/div[2]/button[3]元素点击失败
2023-10-08 11:18:41,451 - [opject.py - 33] - ERROR:打开www.baidu.com网页失败
2023-10-08 11:33:54,575 - [opject.py - 69] - ERROR:元素为//*[@id="app"]/div/div[2]/div[2]/div[1]/span/div/span/input输入的值为C:\Users\HUAWEI\Desktop\2.zip失败
2023-10-18 11:26:09,141 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020372B8D460>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/f8ee2b0dc2818000daa539eae90aa503
2023-10-18 11:26:09,141 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020372B8D460>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/f8ee2b0dc2818000daa539eae90aa503
2023-10-18 11:33:01,020 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DC5B38D3A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/e82bec8be23ce72bb81a94053a5813fa
2023-10-18 11:33:01,020 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DC5B38D3A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/e82bec8be23ce72bb81a94053a5813fa
2023-10-18 11:33:05,117 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DC5BDBB370>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/e82bec8be23ce72bb81a94053a5813fa
2023-10-18 11:33:05,117 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DC5BDBB370>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/e82bec8be23ce72bb81a94053a5813fa
2023-10-18 11:37:40,003 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026164F6D460>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/447ebd2ce1a85fb45c1e10dfc37f0239
2023-10-18 11:37:40,003 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026164F6D460>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/447ebd2ce1a85fb45c1e10dfc37f0239
2023-10-18 14:06:26,906 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000145D302D400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/52a9c88fbb6a4834c7075a8db1c1a82e
2023-10-18 14:06:26,906 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000145D302D400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/52a9c88fbb6a4834c7075a8db1c1a82e
2023-10-18 14:06:30,997 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000145D3A5B3A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/52a9c88fbb6a4834c7075a8db1c1a82e
2023-10-18 14:06:30,997 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000145D3A5B3A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/52a9c88fbb6a4834c7075a8db1c1a82e
2023-10-18 14:16:27,930 - [test_contract_aptos.py - 51] - INFO:测试编号:1,测试标题:创建项目aptos_staking,执行成功！
2023-10-18 14:16:27,930 - [test_contract_aptos.py - 51] - INFO:测试编号:1,测试标题:创建项目aptos_staking,执行成功！
2023-10-18 14:16:49,686 - [test_contract_aptos.py - 51] - INFO:测试编号:2,测试标题:创建项目aptos_vesting,执行成功！
2023-10-18 14:16:49,686 - [test_contract_aptos.py - 51] - INFO:测试编号:2,测试标题:创建项目aptos_vesting,执行成功！
2023-10-18 14:17:10,804 - [test_contract_aptos.py - 51] - INFO:测试编号:3,测试标题:创建项目aptos_lending,执行成功！
2023-10-18 14:17:10,804 - [test_contract_aptos.py - 51] - INFO:测试编号:3,测试标题:创建项目aptos_lending,执行成功！
2023-10-18 14:17:31,745 - [test_contract_aptos.py - 51] - INFO:测试编号:4,测试标题:创建项目aptos_ToDoList,执行成功！
2023-10-18 14:17:31,745 - [test_contract_aptos.py - 51] - INFO:测试编号:4,测试标题:创建项目aptos_ToDoList,执行成功！
2023-10-18 14:18:45,296 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000244832DD430>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9ecac7c2d8b42e8e5d32d26e9336bc62
2023-10-18 14:18:45,296 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000244832DD430>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9ecac7c2d8b42e8e5d32d26e9336bc62
2023-10-18 14:18:49,387 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024483E7A220>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9ecac7c2d8b42e8e5d32d26e9336bc62
2023-10-18 14:18:49,387 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024483E7A220>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9ecac7c2d8b42e8e5d32d26e9336bc62
2023-10-18 14:18:53,497 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024483CED940>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9ecac7c2d8b42e8e5d32d26e9336bc62
2023-10-18 14:18:53,497 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024483CED940>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9ecac7c2d8b42e8e5d32d26e9336bc62
2023-10-18 14:22:54,783 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029B1292E5E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/e17c19ce088e62bf08654ad708a12281
2023-10-18 14:22:54,783 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029B1292E5E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/e17c19ce088e62bf08654ad708a12281
2023-10-18 14:22:58,871 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029B13F61520>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/e17c19ce088e62bf08654ad708a12281
2023-10-18 14:22:58,871 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029B13F61520>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/e17c19ce088e62bf08654ad708a12281
2023-10-18 14:23:02,957 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029B13F61580>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/e17c19ce088e62bf08654ad708a12281
2023-10-18 14:23:02,957 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029B13F61580>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/e17c19ce088e62bf08654ad708a12281
2023-10-18 14:27:41,778 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ABD552E400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/cb6f7447c3f2603ad23de86c9ebd2c90
2023-10-18 14:27:41,778 - [connectionpool.py - 823] - WARNING:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ABD552E400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/cb6f7447c3f2603ad23de86c9ebd2c90
2023-10-18 14:30:19,804 - [test_contract_evm.py - 51] - INFO:测试编号:1,测试标题:创建项目ERC4907,执行成功！
2023-10-18 14:30:19,804 - [test_contract_evm.py - 51] - INFO:测试编号:1,测试标题:创建项目ERC4907,执行成功！
2023-10-18 14:31:43,040 - [opject.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-10-18 14:31:43,040 - [opject.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-10-18 14:31:43,040 - [opject.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-10-18 14:32:06,103 - [test_contract_evm.py - 51] - INFO:测试编号:3,测试标题:创建项目Edition,执行成功！
2023-10-18 14:32:06,103 - [test_contract_evm.py - 51] - INFO:测试编号:3,测试标题:创建项目Edition,执行成功！
2023-10-18 14:32:06,103 - [test_contract_evm.py - 51] - INFO:测试编号:3,测试标题:创建项目Edition,执行成功！
2023-10-18 14:32:32,187 - [test_contract_evm.py - 51] - INFO:测试编号:4,测试标题:创建项目ERC721,执行成功！
2023-10-18 14:32:32,187 - [test_contract_evm.py - 51] - INFO:测试编号:4,测试标题:创建项目ERC721,执行成功！
2023-10-18 14:32:32,187 - [test_contract_evm.py - 51] - INFO:测试编号:4,测试标题:创建项目ERC721,执行成功！
2023-10-18 14:32:58,165 - [test_contract_evm.py - 51] - INFO:测试编号:6,测试标题:创建项目token,执行成功！
2023-10-18 14:32:58,165 - [test_contract_evm.py - 51] - INFO:测试编号:6,测试标题:创建项目token,执行成功！
2023-10-18 14:32:58,165 - [test_contract_evm.py - 51] - INFO:测试编号:6,测试标题:创建项目token,执行成功！
2023-10-18 14:35:45,406 - [test_contract_evm.py - 51] - INFO:测试编号:2,测试标题:创建项目NFT,执行成功！
2023-10-18 14:35:45,406 - [test_contract_evm.py - 51] - INFO:测试编号:2,测试标题:创建项目NFT,执行成功！
2023-10-20 15:31:07,243 - [test_contract_aptos.py - 51] - INFO:测试编号:1,测试标题:创建项目aptos_staking,执行成功！
2023-10-20 15:31:07,243 - [test_contract_aptos.py - 51] - INFO:测试编号:1,测试标题:创建项目aptos_staking,执行成功！
2023-10-20 15:31:27,084 - [test_contract_aptos.py - 51] - INFO:测试编号:2,测试标题:创建项目aptos_vesting,执行成功！
2023-10-20 15:31:27,084 - [test_contract_aptos.py - 51] - INFO:测试编号:2,测试标题:创建项目aptos_vesting,执行成功！
2023-10-20 15:31:48,295 - [test_contract_aptos.py - 51] - INFO:测试编号:3,测试标题:创建项目aptos_lending,执行成功！
2023-10-20 15:31:48,295 - [test_contract_aptos.py - 51] - INFO:测试编号:3,测试标题:创建项目aptos_lending,执行成功！
2023-10-20 15:32:07,941 - [test_contract_aptos.py - 51] - INFO:测试编号:4,测试标题:创建项目aptos_ToDoList,执行成功！
2023-10-20 15:32:07,941 - [test_contract_aptos.py - 51] - INFO:测试编号:4,测试标题:创建项目aptos_ToDoList,执行成功！
2023-10-20 15:32:28,122 - [test_contract_aptos.py - 51] - INFO:测试编号:5,测试标题:创建项目aptos_marketplace_contract,执行成功！
2023-10-20 15:32:28,122 - [test_contract_aptos.py - 51] - INFO:测试编号:5,测试标题:创建项目aptos_marketplace_contract,执行成功！
2023-10-20 15:32:48,227 - [test_contract_aptos.py - 51] - INFO:测试编号:6,测试标题:创建项目aptos_NFT_marketplace,执行成功！
2023-10-20 15:32:48,227 - [test_contract_aptos.py - 51] - INFO:测试编号:6,测试标题:创建项目aptos_NFT_marketplace,执行成功！
2023-10-20 15:33:38,358 - [test_contract_evm.py - 51] - INFO:测试编号:1,测试标题:创建项目ERC4907,执行成功！
2023-10-20 15:33:38,358 - [test_contract_evm.py - 51] - INFO:测试编号:1,测试标题:创建项目ERC4907,执行成功！
2023-10-20 15:34:04,429 - [test_contract_evm.py - 51] - INFO:测试编号:2,测试标题:创建项目NFT,执行成功！
2023-10-20 15:34:04,429 - [test_contract_evm.py - 51] - INFO:测试编号:2,测试标题:创建项目NFT,执行成功！
2023-10-20 15:34:32,141 - [test_contract_evm.py - 51] - INFO:测试编号:3,测试标题:创建项目Edition,执行成功！
2023-10-20 15:34:32,141 - [test_contract_evm.py - 51] - INFO:测试编号:3,测试标题:创建项目Edition,执行成功！
2023-10-20 15:35:57,024 - [opject.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-10-20 15:35:57,024 - [opject.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-10-20 15:35:57,024 - [opject.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-10-20 15:37:16,387 - [opject.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-10-20 15:37:16,387 - [opject.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-10-20 15:37:16,387 - [opject.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-10-20 15:37:16,387 - [opject.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-10-20 15:42:45,590 - [test_contract_evm.py - 95] - INFO:测试编号:1,测试标题:检查项目ERC4907,执行成功！
2023-10-20 15:42:45,590 - [test_contract_evm.py - 95] - INFO:测试编号:1,测试标题:检查项目ERC4907,执行成功！
2023-10-20 15:42:45,590 - [test_contract_evm.py - 95] - INFO:测试编号:1,测试标题:检查项目ERC4907,执行成功！
2023-10-20 15:42:45,590 - [test_contract_evm.py - 95] - INFO:测试编号:1,测试标题:检查项目ERC4907,执行成功！
2023-11-01 15:28:15,969 - [opject.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-11-01 15:28:15,969 - [opject.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-11-01 15:28:15,969 - [opject.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-11-01 15:33:32,787 - [opject.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-11-01 15:33:32,787 - [opject.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-11-01 15:33:32,787 - [opject.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-11-01 15:48:25,800 - [test_contract_evm.py - 51] - INFO:测试编号:1,测试标题:创建项目ERC4907,执行成功！
2023-11-01 15:48:25,800 - [test_contract_evm.py - 51] - INFO:测试编号:1,测试标题:创建项目ERC4907,执行成功！
2023-11-01 15:48:54,908 - [test_contract_evm.py - 51] - INFO:测试编号:2,测试标题:创建项目NFT,执行成功！
2023-11-01 15:48:54,908 - [test_contract_evm.py - 51] - INFO:测试编号:2,测试标题:创建项目NFT,执行成功！
2023-11-01 15:49:24,510 - [test_contract_evm.py - 51] - INFO:测试编号:3,测试标题:创建项目Edition,执行成功！
2023-11-01 15:49:24,510 - [test_contract_evm.py - 51] - INFO:测试编号:3,测试标题:创建项目Edition,执行成功！
2023-11-01 15:49:53,097 - [test_contract_evm.py - 51] - INFO:测试编号:4,测试标题:创建项目ERC721,执行成功！
2023-11-01 15:49:53,097 - [test_contract_evm.py - 51] - INFO:测试编号:4,测试标题:创建项目ERC721,执行成功！
2023-11-01 15:50:57,585 - [test_contract_evm.py - 51] - INFO:测试编号:5,测试标题:创建项目Uniswapper,执行成功！
2023-11-01 15:50:57,585 - [test_contract_evm.py - 51] - INFO:测试编号:5,测试标题:创建项目Uniswapper,执行成功！
2023-11-01 15:51:38,099 - [test_contract_evm.py - 51] - INFO:测试编号:6,测试标题:创建项目token,执行成功！
2023-11-01 15:51:38,099 - [test_contract_evm.py - 51] - INFO:测试编号:6,测试标题:创建项目token,执行成功！
2023-11-01 15:52:10,230 - [test_contract_evm.py - 51] - INFO:测试编号:7,测试标题:创建项目FunctionsConsumer,执行成功！
2023-11-01 15:52:10,230 - [test_contract_evm.py - 51] - INFO:测试编号:7,测试标题:创建项目FunctionsConsumer,执行成功！
2023-11-01 15:52:40,948 - [test_contract_evm.py - 51] - INFO:测试编号:8,测试标题:创建项目Withdraw,执行成功！
2023-11-01 15:52:40,948 - [test_contract_evm.py - 51] - INFO:测试编号:8,测试标题:创建项目Withdraw,执行成功！
2023-11-01 15:53:14,536 - [test_contract_evm.py - 51] - INFO:测试编号:9,测试标题:创建项目Swap,执行成功！
2023-11-01 15:53:14,536 - [test_contract_evm.py - 51] - INFO:测试编号:9,测试标题:创建项目Swap,执行成功！
2023-11-01 15:53:48,381 - [test_contract_evm.py - 51] - INFO:测试编号:10,测试标题:创建项目MultiOutput,执行成功！
2023-11-01 15:53:48,381 - [test_contract_evm.py - 51] - INFO:测试编号:10,测试标题:创建项目MultiOutput,执行成功！
2023-11-01 15:54:17,937 - [test_contract_evm.py - 51] - INFO:测试编号:11,测试标题:创建项目Message,执行成功！
2023-11-01 15:54:17,937 - [test_contract_evm.py - 51] - INFO:测试编号:11,测试标题:创建项目Message,执行成功！
2023-11-01 15:54:46,243 - [test_contract_evm.py - 51] - INFO:测试编号:12,测试标题:创建项目MultiValueTransfer,执行成功！
2023-11-01 15:54:46,243 - [test_contract_evm.py - 51] - INFO:测试编号:12,测试标题:创建项目MultiValueTransfer,执行成功！
2023-11-01 15:55:18,450 - [test_contract_evm.py - 51] - INFO:测试编号:13,测试标题:创建项目Counter,执行成功！
2023-11-01 15:55:18,450 - [test_contract_evm.py - 51] - INFO:测试编号:13,测试标题:创建项目Counter,执行成功！
2023-11-01 15:55:49,379 - [test_contract_evm.py - 51] - INFO:测试编号:14,测试标题:创建项目NFT_Zeta,执行成功！
2023-11-01 15:55:49,379 - [test_contract_evm.py - 51] - INFO:测试编号:14,测试标题:创建项目NFT_Zeta,执行成功！
2023-11-01 15:56:24,363 - [test_contract_evm.py - 51] - INFO:测试编号:15,测试标题:创建项目GreenfieldMarketplace,执行成功！
2023-11-01 15:56:24,363 - [test_contract_evm.py - 51] - INFO:测试编号:15,测试标题:创建项目GreenfieldMarketplace,执行成功！
2023-11-01 15:59:12,918 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 15:59:12,918 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 15:59:12,918 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:01:57,971 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:01:57,971 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:01:57,971 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:01:57,971 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:04:42,447 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:04:42,447 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:04:42,447 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:04:42,447 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:04:42,447 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:07:27,258 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:07:27,258 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:07:27,258 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:07:27,258 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:07:27,258 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:07:27,258 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:09:19,680 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:09:19,680 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:09:19,680 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:09:19,680 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:09:19,680 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:09:19,680 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:09:19,680 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:12:01,150 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:12:01,150 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:12:01,150 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:12:01,150 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:12:01,150 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:12:01,150 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:12:01,150 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:12:01,150 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:17:12,109 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:17:12,109 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:17:12,109 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:17:12,109 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:17:12,109 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:17:12,109 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:17:12,109 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:17:12,109 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:17:12,109 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:24:10,288 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:24:10,288 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:24:10,288 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:24:10,288 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:24:10,288 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:24:10,288 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:24:10,288 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:24:10,288 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:24:10,288 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:24:10,288 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:31:23,187 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:31:23,187 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:31:23,187 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:31:23,187 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:31:23,187 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:31:23,187 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:31:23,187 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:31:23,187 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:31:23,187 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:31:23,187 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:31:23,187 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:37:38,817 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:37:38,817 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:37:38,817 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:37:38,817 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:37:38,817 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:37:38,817 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:37:38,817 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:37:38,817 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:37:38,817 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:37:38,817 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:37:38,817 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:37:38,817 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:44:01,235 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:44:01,235 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:44:01,235 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:44:01,235 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:44:01,235 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:44:01,235 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:44:01,235 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:44:01,235 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:44:01,235 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:44:01,235 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:44:01,235 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:44:01,235 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:44:01,235 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:49:52,282 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:49:52,282 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:49:52,282 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:49:52,282 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:49:52,282 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:49:52,282 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:49:52,282 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:49:52,282 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:49:52,282 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:49:52,282 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:49:52,282 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:49:52,282 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:49:52,282 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:49:52,282 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:55:40,215 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:55:40,215 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:55:40,215 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:55:40,215 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:55:40,215 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:55:40,215 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:55:40,215 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:55:40,215 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:55:40,215 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:55:40,215 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:55:40,215 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:55:40,215 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:55:40,215 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:55:40,215 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 16:55:40,215 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:01:27,521 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:01:27,521 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:01:27,521 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:01:27,521 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:01:27,521 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:01:27,521 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:01:27,521 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:01:27,521 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:01:27,521 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:01:27,521 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:01:27,521 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:01:27,521 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:01:27,521 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:01:27,521 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:01:27,521 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:01:27,521 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:02:34,938 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:02:34,938 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:02:34,938 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:02:34,938 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:02:34,938 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:02:34,938 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:02:34,938 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:02:34,938 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:02:34,938 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:02:34,938 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:02:34,938 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:02:34,938 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:02:34,938 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:02:34,938 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:02:34,938 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:02:34,938 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-01 17:02:34,938 - [opject.py - 160] - ERROR:元素为//*[@id="layout-default"]/section/main/div/div[4]/div/div[2]/div[2]/div/div/div/div/div/table/tbody/tr/td[5]/label[1]查询文本失败
2023-11-07 17:13:58,760 - [object_page.py - 215] - ERROR:元素为【//*[@id="app"]/div/div[2]/div[2]/div[1]/div[1]/span/div/span/input】上传文件失败
2023-11-20 11:10:22,521 - [test_contract_aptos.py - 51] - INFO:测试编号:1,测试标题:创建项目aptos_staking,执行成功！
2023-11-20 11:10:22,521 - [test_contract_aptos.py - 51] - INFO:测试编号:1,测试标题:创建项目aptos_staking,执行成功！
2023-11-20 11:10:43,343 - [test_contract_aptos.py - 51] - INFO:测试编号:2,测试标题:创建项目aptos_vesting,执行成功！
2023-11-20 11:10:43,343 - [test_contract_aptos.py - 51] - INFO:测试编号:2,测试标题:创建项目aptos_vesting,执行成功！
2023-11-20 11:11:10,734 - [test_contract_aptos.py - 51] - INFO:测试编号:3,测试标题:创建项目aptos_lending,执行成功！
2023-11-20 11:11:10,734 - [test_contract_aptos.py - 51] - INFO:测试编号:3,测试标题:创建项目aptos_lending,执行成功！
2023-11-20 11:11:30,676 - [test_contract_aptos.py - 51] - INFO:测试编号:4,测试标题:创建项目aptos_ToDoList,执行成功！
2023-11-20 11:11:30,676 - [test_contract_aptos.py - 51] - INFO:测试编号:4,测试标题:创建项目aptos_ToDoList,执行成功！
2023-11-20 11:11:51,369 - [test_contract_aptos.py - 51] - INFO:测试编号:5,测试标题:创建项目aptos_marketplace_contract,执行成功！
2023-11-20 11:11:51,369 - [test_contract_aptos.py - 51] - INFO:测试编号:5,测试标题:创建项目aptos_marketplace_contract,执行成功！
2023-11-20 11:12:18,592 - [test_contract_aptos.py - 51] - INFO:测试编号:6,测试标题:创建项目aptos_NFT_marketplace,执行成功！
2023-11-20 11:12:18,592 - [test_contract_aptos.py - 51] - INFO:测试编号:6,测试标题:创建项目aptos_NFT_marketplace,执行成功！
2023-11-20 11:12:38,906 - [test_contract_aptos.py - 51] - INFO:测试编号:7,测试标题:创建项目aptos_raffle,执行成功！
2023-11-20 11:12:38,906 - [test_contract_aptos.py - 51] - INFO:测试编号:7,测试标题:创建项目aptos_raffle,执行成功！
2023-11-20 11:12:59,843 - [test_contract_aptos.py - 51] - INFO:测试编号:8,测试标题:创建项目aptos_candymachine,执行成功！
2023-11-20 11:12:59,843 - [test_contract_aptos.py - 51] - INFO:测试编号:8,测试标题:创建项目aptos_candymachine,执行成功！
2023-11-20 11:13:20,586 - [test_contract_aptos.py - 51] - INFO:测试编号:9,测试标题:创建项目aptos_merkproof,执行成功！
2023-11-20 11:13:20,586 - [test_contract_aptos.py - 51] - INFO:测试编号:9,测试标题:创建项目aptos_merkproof,执行成功！
2023-11-20 11:14:09,922 - [test_contract_aptos.py - 51] - INFO:测试编号:10,测试标题:创建项目aptos_hello_blockchain,执行成功！
2023-11-20 11:14:09,922 - [test_contract_aptos.py - 51] - INFO:测试编号:10,测试标题:创建项目aptos_hello_blockchain,执行成功！
2023-11-20 11:14:29,525 - [test_contract_aptos.py - 51] - INFO:测试编号:11,测试标题:创建项目aptos_warkade,执行成功！
2023-11-20 11:14:29,525 - [test_contract_aptos.py - 51] - INFO:测试编号:11,测试标题:创建项目aptos_warkade,执行成功！
2023-11-20 11:14:50,728 - [test_contract_aptos.py - 51] - INFO:测试编号:12,测试标题:创建项目aptos_tokenv2_wrapper,执行成功！
2023-11-20 11:14:50,728 - [test_contract_aptos.py - 51] - INFO:测试编号:12,测试标题:创建项目aptos_tokenv2_wrapper,执行成功！
2023-11-20 11:15:30,814 - [test_contract_aptos.py - 96] - INFO:测试编号:1,测试标题:['创建项目aptos_staking', '检查项目aptos_staking', '构建项目aptos_staking', '部署项目aptos_staking', '删除项目aptos_staking'],执行成功！
2023-11-20 11:15:30,814 - [test_contract_aptos.py - 96] - INFO:测试编号:1,测试标题:['创建项目aptos_staking', '检查项目aptos_staking', '构建项目aptos_staking', '部署项目aptos_staking', '删除项目aptos_staking'],执行成功！
2023-11-20 11:18:38,270 - [test_contract_sui.py - 51] - INFO:测试编号:1,测试标题:创建项目sui_nfts,执行成功！
2023-11-20 11:18:38,270 - [test_contract_sui.py - 51] - INFO:测试编号:1,测试标题:创建项目sui_nfts,执行成功！
2023-11-20 11:20:21,118 - [object_page.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-11-20 11:20:21,118 - [object_page.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-11-20 11:20:21,118 - [object_page.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-11-20 11:21:07,380 - [object_page.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[1]/div[2]/button[3]元素点击失败
2023-11-20 11:21:07,380 - [object_page.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[1]/div[2]/button[3]元素点击失败
2023-11-20 11:21:07,380 - [object_page.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[1]/div[2]/button[3]元素点击失败
2023-11-20 11:21:07,380 - [object_page.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[1]/div[2]/button[3]元素点击失败
2023-11-20 11:21:39,075 - [object_page.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[1]/div[2]/button[3]元素点击失败
2023-11-20 11:21:39,075 - [object_page.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[1]/div[2]/button[3]元素点击失败
2023-11-20 11:21:39,075 - [object_page.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[1]/div[2]/button[3]元素点击失败
2023-11-20 11:21:39,075 - [object_page.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[1]/div[2]/button[3]元素点击失败
2023-11-20 11:21:39,075 - [object_page.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[1]/div[2]/button[3]元素点击失败
2023-11-20 11:22:44,605 - [object_page.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-11-20 11:22:44,605 - [object_page.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-11-20 11:22:44,605 - [object_page.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-11-20 11:22:44,605 - [object_page.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-11-20 11:22:44,605 - [object_page.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
2023-11-20 11:22:44,605 - [object_page.py - 88] - ERROR://*[@id="layout-default"]/section/main/div/div[2]/button元素点击失败
